### ISSUE TITLE
Warn on large packages/many files

### ISSUE THREAD

**Issue by sindresorhus** [bower/registry#10]
*this pertains to the server rewrite*

Performance is a big focus in the server and client rewrite and to achieve this we have help authors to help improve our performance.

A big bottleneck is unnecessary large packages from authors not using the `ignore` field to ignore unneeded files. With a large test suite, fixtures and other junk, this can make the package considerably larger than needed. We should come up with an heuristic that warns authors when they might have forgotten to do their part.

npm has this problem big time. Almost no one uses .npmignore, which makes all packages larger than they would need to.

-

We also need to better document the benefit of authors using the `ignore` key.

**Comment by sheerun** [comment]
It has been solver as a warn in bower/bower
