### ISSUE TITLE
jquery-jsonrpc package points to non-existent repository

### ISSUE THREAD

**Issue by tchajed** [bower/registry#103]
I'm seeing a jquery-jsonrpc package when I `bower search` and in the raw list from `http://bower.herokuapp.com/packages` pointing to the repository <https://github.com/quiquelores/jquery-jsonrpc>, which doesn't exist.

I'm trying to register another jquery-jsonrpc implementation that actually does exist and can't because of this package; could you manually clear it out?

**Comment by sheerun** [comment]
It seems this issue has been resolved.
