### ISSUE TITLE
UnRegister packages in private instance of Bower Registry

### ISSUE THREAD

**Issue by santbob** [bower/registry#105]
HI 

We are running a private registry for bower for our internal components and we need to remove/unregister certain packages. Is there a way to do it.

Curl delete dosent help.

**Comment by sheerun** [comment]
With this registry implementation you can only unregister public packages hosted on GitHub.com.

You can implement `isOwner` function in `lib/routes/packages.js` by yourself, for example:

```
function isOwner (packageName, token, callback) {
  callback(null, true);
}
```

PR with better `isOwner` handling is welcome.
