### ISSUE TITLE
Show something / redirect on https://bower.herokuapp.com

### ISSUE THREAD

**Issue by sheerun** [bower/registry#106]
Many people are confused by current homepage of registry, especially it is mentioned when registering new package, see: https://github.com/bower/bower/issues/1612

**Comment by patrickkettner** [comment]
something like 

```javascript
app.get('/', function(req, res){
  res.redirect(301, 'http://bower.io/');
});
```

**Comment by sheerun** [comment]
Maybe 302 is more appropriate?

**Comment by patrickkettner** [comment]
hmm...how is it temporary?

On Sun, Jan 4, 2015 at 10:06 PM, Adam Stankiewicz <notifications@github.com>
wrote:

> Maybe 302 is more appropriate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bower/registry/issues/106#issuecomment-68663547>.
>



-- 
patrick

**Comment by sheerun** [comment]
For example in future we decide to point to http://bower.io/search/ instead?

**Comment by patrickkettner** [comment]
[from Matt Cutts...](https://www.mattcutts.com/blog/seo-advice-discussing-302-redirects/)

>  By definition, those are redirects from one domain A.com to another domain B.com that are claimed to be temporary; that is, the web server on A.com could always change its mind and start showing content on A.com again

302 it is

**Comment by desandro** [comment]
Is this working? https://bower.herokuapp.com is still  `Cannot GET /`

**Comment by sheerun** [comment]
@desandro Someone forgot to deploy. I just did it.

**Comment by teddyhwang** [comment]
https://bower.herokuapp.com seems to be down again

**Comment by sheerun** [comment]
@teddyhwang It's not appropriate issue for reporting downtimes.

https://gitter.im/bower/bower
