### ISSUE TITLE
https://bower.herokuapp.com/ is down. Gives application error

### ISSUE THREAD

**Issue by mikaelhm** [bower/registry#108]
The registry app seems to be down.

gives application error.

![skaermbillede 2015-01-12 10 46 00](https://cloud.githubusercontent.com/assets/698065/5708712/4a2aab08-9a48-11e4-9a18-3483d2a2a4d2.png)

**Comment by mikaelhm** [comment]
Seems to be fixed already.

**Comment by dubcanada** [comment]
Back down again.

**Comment by v1p** [comment]
It's complaining about a Timeout while running a test in travis build report

**Comment by v1p** [comment]
Perhaps tests need more time to run.

**Comment by sheerun** [comment]
Most likely failed tests has nothing to do with downtime. It was probably overload.

**Comment by v1p** [comment]
Yeah probably overload was the culprit

**Comment by sheerun** [comment]
The cause of crash was high CPU load.

Heroku agreed to sponsor Bower's hosting with $150/month. I've added another small dyno.

We also have Heroku metrics now, so we can monitor Bower's registry performance.

Cheers and thanks for Heroku!
