### ISSUE TITLE
Pure is missing

### ISSUE THREAD

**Issue by jamesalley** [bower/registry#109]
[Pure] (https://github.com/yahoo/pure/) is no longer listed at http://bower.io/search/ and `$ bower install --save pure` does not work:  _Request to https://bower.herokuapp.com/packages/pure failed with 503._ I've heard rumors there were problems with the registry lately?

**Comment by sheerun** [comment]
Registry went down. It's back..

**Comment by jamesalley** [comment]
Thanks, verified! Good work.
