### ISSUE TITLE
Deal somehow with stale packages

### ISSUE THREAD

**Issue by sheerun** [bower/registry#110]
I think the best idea is to create web interface for listing stale packages, and let registry editors remove them manually. I think we don't want any automation because we can easily delete half of registry by mistake.

Followup of: #69, #72

**Comment by davidjbradshaw** [comment]
I've just added these tickets to help understand the size of the issue and possibly be used to update the registry. 

* #113 List of 3815 projects missing bower.json file.
* #114 List of 1556 projects that have moved on GitHub, with old and new locations.
* #115 List of 1248 projects that have been deleted from GitHub.

**Comment by patrickkettner** [comment]
I do not believe #113 is relevant. we can't control wether or not a repo has a bower.json

**Comment by sheerun** [comment]
The only concern I have is following case:

1. Developer uses package xxx
2. This package gets removed by its author
3. We removed package from registry
4. Someone registered malicious package under xxx name
5. Developer performs `bundle install`, and malicious xxx package is installed, instead just erroring that package got removed from GitHub..
