### ISSUE TITLE
Registered URLs don't update when changed on GitHub (breaks web search)

### ISSUE THREAD

**Issue by davidjbradshaw** [bower/registry#112]
If I register a package as `https://github.com/djb/foo` and then rename it to `https://github.com/djb/bar` the bower registry doesn't update the address, even if I change it in `bower.json`

This is a problem, because the web search gets a 404 when it then calls `https://api.github.com/repos/djb/foo` and then the project drops out of the web search results.

See the following for more details:
bower/search-server/issues/20
bower/search/issues/36

**Comment by sheerun** [comment]
This should be implemented in bower/bower resolver instead
