### ISSUE TITLE
Fix Unregistration of transfered repos

### ISSUE THREAD

**Issue by samccone** [bower/registry#116]
#### Steps to reproduce

* create a repo under user X
* user X registers the repo on bower github.com/X/foobar
* user X transfers the repo to user Y
* user Y wants to change the registry to a new location
* user Y tries to unregister (however it fails)

This is because of 

```js
var owner = pathParts[1];
var repo = path.basename(pathParts[2], '.git');
```
https://github.com/samccone/registry/blob/master/lib/routes/packages.js#L43-L44

Which pulls the contributors from the original registration url instead of the updated location of the project (since it has been moved). 

![screen shot 2015-02-25 at 1 53 13 pm](https://cloud.githubusercontent.com/assets/883126/6377939/ceb0accc-bcf5-11e4-8fdb-0413773ec311.png)

#### Solution

* The simple solution here, is to make sure that when you get the http version of the repo, it does not 301 redirect to the new repo

For instance:

```
curl -I https://github.com/marionettejs/testing
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Location: https://github.com/samccone/testing
```

Clearly the permissions should be checked against `samccone/testing`

--------

These are just my thoughts after chatting with @desandro, let me know If I am missing something or whatnot. :+1: 

The ultimate goal here is to unburden the people that have been doing a great job manually doing the unregistration over at https://github.com/bower/bower/issues/120

**Comment by desandro** [comment]
:+1:

**Comment by samccone** [comment]
welp there we are thanks @sheerun was going to work on this on Friday, been out on site consulting this week so time has been at a minimum thanks for doing it!

**Comment by sheerun** [comment]
thanks for research!
