### ISSUE TITLE
Broken package name

### ISSUE THREAD

**Issue by fatlinesofcode** [bower/registry#118]
Hi, while attempting to remove a bad version I unregistered a package thinking I could just register it again. However the package name was in CamelCase and I was unable to re-register using the original name. I had to register the name in lowercase and now Im getting lots of package not found issues. 

https://github.com/fatlinesofcode/ngDraggable/issues/100

Its possible to alias the old camelcase name?

Old name ngDraggable, new name ngdraggable.

And just to add to the confusion someone else has squatted ng-draggable

**Comment by sheerun** [comment]
Hey. I renamed package back to ngDraggable.

**Comment by fatlinesofcode** [comment]
too easy, thanks
