### ISSUE TITLE
thymol not found by search

### ISSUE THREAD

**Issue by jjbenson** [bower/registry#120]
The thymol project is no longer found as a search result, although the packages query looks fine:

curl http://bower.herokuapp.com/packages/thymol
{"name":"thymol","url":"git://github.com/thymol/thymol.js.git","hits":26}

Can you please provide any insight into this?

**Comment by samccone** [comment]
You do not have a bower.json file in your repo
https://github.com/thymol/thymol.js

Thus it will not show up. Add it to your project and you should be all set :+1:
