### ISSUE TITLE
Remove crypto-js

### ISSUE THREAD

**Issue by kirill-konshin** [bower/registry#121]
A follow up for https://github.com/bower/bower/issues/120#issuecomment-85257405 and https://github.com/bower/bower/issues/120#issuecomment-84255071

This package cannot be unregistered by author since author has deleted the Github repository.

Please delete manually.

Or replace the package reference
From: git://github.com/Jeff-Mott-OR/CryptoJS.git
To: git://github.com/evanvosberg/crypto-js.git

**Comment by desandro** [comment]
Re-registered `crypto-js` to `git://github.com/evanvosberg/crypto-js.git` :arrow_right: cc @evanvosberg

**Comment by kirill-konshin** [comment]
```sh
dis$ bower install crypto-js --save
bower crypto-js#*           not-cached git://github.com/Jeff-Mott-OR/CryptoJS.git#*
bower crypto-js#*              resolve git://github.com/Jeff-Mott-OR/CryptoJS.git#*
bower crypto-js#*           not-cached git://github.com/Jeff-Mott-OR/CryptoJS.git#*
bower crypto-js#*              resolve git://github.com/Jeff-Mott-OR/CryptoJS.git#*
bower crypto-js#*              ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/Jeff-Mott-OR/CryptoJS.git", exit code of #128
```

Still points to the same deleted repo. Please double check.

**Comment by kirill-konshin** [comment]
Cleaned the cache, after that works OK. But I don't think that this is user-friendly...

**Comment by patrickkettner** [comment]
what isn't, caches?

**Comment by kirill-konshin** [comment]
Caches...

**Comment by kirill-konshin** [comment]
Users have to manually reset caches in case package was relocated and user has seen original URL.
