### ISSUE TITLE
Uppercase to lowercase

### ISSUE THREAD

**Issue by dbox** [bower/registry#123]
@sheerun Would you mind changing `RRSSB` to `rrssb`. Thank you!

I've done it in our bower.json file: https://github.com/kni-labs/rrssb

**Comment by sheerun** [comment]
I think you can do it by yourself. Just unregister and register it again :)

Also maybe it's good idea to register both if RRSSB is already used by some people.

**Comment by dbox** [comment]
Ah. Was worried that would break it for people.
