### ISSUE TITLE
duplicate package release request: stage.js

### ISSUE THREAD

**Issue by shakiba** [bower/registry#125]
[This](https://github.com/bluekvirus/Stage.js) repo is registered as both "stage" and "stage.js", can you please release "stage.js" so that I can use it for [my repo](https://github.com/piqnt/stage.js). I have just registered stage.js with npm as well.

@bluekvirus

**Comment by desandro** [comment]
You are allowed to register the same repo with multiple package names. Switching over one repo to another with the same package name would also break compatibility. I recommend using another name :whale:
