### ISSUE TITLE
Unregistering a Package

### ISSUE THREAD

**Issue by barefootcss** [bower/registry#126]
Hope this is not confusing...

* I created a git repository and registered it with bower
* I unregistered and deleted the repository thinking I didn't need it.
* Then, I tried repeating the progress and it told me I'm not the collaborator

Here are some of the errors I received.

**When unregistering bare-normalize:**

     EFORBIDDEN    Must be a collaborator on GitHub.com repository

**When registering bare-normalize:**

     EDUPLICATE    Duplicate package

**When getting `bower info` on bare-normalize**

1st Attempt

      Returned the JSON

2nd Attempt

     ECMDERR       Failed to execute "git ls--remote -tags"

I am logged into bower as proper git contributer too who registered the package.

**Comment by barefootcss** [comment]
I'm still unable to do this. The bower registry doesn't show the package, but I am still unable to register it with that name.

**Comment by sheerun** [comment]
Unregistered..
