### ISSUE TITLE
best way to construct bower dependencies graph

### ISSUE THREAD

**Issue by anvaka** [bower/registry#128]
Hello guys,

I was going through the source code, trying to understand what's the most efficient way to construct all dependencies graph for the bower registry.

The only solution I've found so far is to download all dependencies from https://bower-component-list.herokuapp.com/ and then for each dependency go to repository and try to find `bower.json` file.

Is there any faster way of getting dependencies?

Thank you!

**Comment by anvaka** [comment]
I ended up crawling `bower.json` for each found module: https://github.com/anvaka/allbower/blob/master/lib/getAllPackages.js

**Comment by sheerun** [comment]
Yes, currently it's the only way
