### ISSUE TITLE
Delist fork of the current project

### ISSUE THREAD

**Issue by niemyjski** [bower/registry#130]
I recently took over https://github.com/csnover/TraceKit and listed an newer bower package as the occ branch (https://github.com/occ/TraceKit) that was being used is dead and occ (https://github.com/occ) hasn't responded in a very very long time. I reached out to him last week and have heard nothing back. Could we please get this package delisted so the new and maintained one will be listed :).

**Comment by niemyjski** [comment]
Is there any chance I could get someone to take a look into this?

**Comment by desandro** [comment]
LGTM

`tracekit` is now registered to `git://github.com/csnover/TraceKit.git`

@occ @devinrhode2 - @niemyjski's request to unregister `https://github.com/devinrhode2/TraceKit` was legitimate as the previous package hasn't been updated in years, and it was missing `bower.json`

**Comment by niemyjski** [comment]
Thank you!

I'm still seeing occ listed (looks like it was renamed to traceKit). I think it's safe to delist that one too (old and I pulled in all his changes to the root).
