### ISSUE TITLE
flexslider

### ISSUE THREAD

**Issue by jeffikus** [bower/registry#131]
Hi guys

I see someone has already taken the 'flexslider' name for a bower repo, however, their repo is simply an outdated fork of the official FlexSlider repo. I'm the lead developer and I've registered 'woothemes-flexslider' as a stop gap for now, but I would like to know how I can get the 'flexslider' name please.

Thanks,

**Comment by desandro** [comment]
`flexslider` is registered to `https://github.com/woothemes/FlexSlider`. Is this already correct? Check `bower info flexslider`.

[bower.io/search does not show flexslider](http://bower.io/search/?q=flexslider), but that's a separate issue.

**Comment by jeffikus** [comment]
@desandro interesting, that wasn't like that yesterday, thanks for investigating!

Ok cool so I can simply proceed in the future by updating the bower.json file and tagging accordingly in the FlexSlider repo?

**Comment by desandro** [comment]
Yup. You should be all set :)
