### ISSUE TITLE
change repository for decentraland-core

### ISSUE THREAD

**Issue by maraoz** [bower/registry#133]
Hey, I read opening an issue here is the way to change the repository for a bower package.

Can you change the repository for decentraland-core (http://bower.io/search/?q=decentraland-core) from https://github.com/maraoz/decentraland-core to https://github.com/decentraland/decentraland-core ?

Thanks!

**Comment by desandro** [comment]
As you are a contributor to `maraoz/decentraland-core`, you can [unregister the current package](http://bower.io/docs/creating-packages/#unregister) and re-register it to `decentraland/decentraland-core`

    bower register decentraland-core git://github.com/decentraland/decentraland-core.git

**Comment by maraoz** [comment]
Thanks! It worked!
