### ISSUE TITLE
Change to official repository for jquery.dirtyforms

### ISSUE THREAD

**Issue by NightOwl888** [bower/registry#134]
We have just created a build script and [official distribution repository](https://github.com/NightOwl888/jquery.dirtyforms.dist) for [jquery.dirtyforms](https://github.com/snikch/jquery.dirtyforms). However, someone got tired of waiting for us to create a Bower package and decided to use an [unofficial fork of the repository](https://github.com/strongholder/jquery.dirtyforms) for Bower.

Please update the URL from the unofficial source to the official one.

```
URL is...
git://github.com/strongholder/jquery.dirtyforms.git

URL should be...
git://github.com/NightOwl888/jquery.dirtyforms.dist.git
```

We have already re-released the 1.0.0 version (the only tag) in the unofficial source so it will be a seamless change for end users.

Thanks

**Comment by desandro** [comment]
Thanks for reporting this issue. Changing a registered package could break compatibility, even if it is a fork. Best solution is to register this package under another name. Looks like `dirtyforms` is available.

**Comment by NightOwl888** [comment]
There are 3 Bower packages that depend on this one (which have the dependency specified as jquery.dirtyforms).

```
jquery.dirtyforms.helpers.alwaysdirty
jquery.dirtyforms.helpers.ckeditor
jquery.dirtyforms.helpers.tinymce
```

It would be a major issue to change the name now - I have already submitted to NuGet and jsDelivr as jquery.dirtyforms, and already have NPM ready to go as jquery.dirtyforms. All of [the documentation](https://github.com/snikch/jquery.dirtyforms#download--installation) specifies it as jquery.dirtyforms. It would mean changing everything for consistency sake, which is a huge thing to do at this point.

I don't understand what your issue is with this request. Someone forked our repo and submitted it to Bower (unofficially). Why can't you change it to our (official) repo that is not a fork? Nobody can benefit from the way it is currently configured. Of course, we couldn't actually use our official repo (https://github.com/snikch/jquery.dirtyforms) because your [deployment procedure dictated that a separate distribution repo is required for each component](https://github.com/bower/bower/issues/24), which is why I need you to change it as above. You can confirm that the above repo is [a submodule of the official one](https://github.com/snikch/jquery.dirtyforms/blob/master/.gitmodules), and that I am [a collaborator](https://github.com/snikch/jquery.dirtyforms/issues/72) of the official repo. This is not a fork, it is a distribution repo that we have set up for package managers.

Like I said, the 1.0.0 build is an exact copy of 1.0.0 on the current (unofficial) repo, so this will be a seamless change. I have bug fixes ready to go as 1.1.0, but no way to update the (unofficial) fork that you point to in order to release those changes. Also, the current (unofficial) fork has the dependencies specified incorrectly and they are not installing when using Bower.

So please, for the benefit of everyone and for the sake of consistency, can't you update to the official distribution repo?

**Comment by NightOwl888** [comment]
I contacted the owner of the fork and got this sorted out. Still don't understand why the owner of the official repo doesn't get priority, though.

**Comment by jisaacks** [comment]
> I contacted the owner of the fork and got this sorted out.

I think that is the appropriate way to handle this situation. Unregistering a package from someone without their permission seems bad to me, regardless of whether or not it was an unofficial fork. After all, your license does grant the permission to redistribute.

I am glad you got it resolved though :) :+1:
