### ISSUE TITLE
untangle package naming request: angular-local-storage and ngStorage

### ISSUE THREAD

**Issue by macneib** [bower/registry#135]
HI I'm not the maintainer of either project, but here's the issue :

If someone types:

```
bower install ngStorage 
```

they will install [angularLocalStorage](https://github.com/agrublev/angularLocalStorage)

but if someone types

```
bower install ngstorage 
```

they will install [ngStorage](https://github.com/gsklee/ngStorage)

That doesn't seem right. 

Ref: [ bower ngStorage #78 ](https://github.com/agrublev/angularLocalStorage/issues/78)

Ref: [ bower install messes ngstorage and ngStorage #62 ] (https://github.com/gsklee/ngStorage/issues/62)

I've contacted the owner of angular-local-storage, and requested a change action, however I haven't received a response, and the angularLocalStorage maintainer appears to be inactive on github. :/

I've also read the angular-local-storage readme and it appears that the proper way to install angularLocalStorage is the following:

```
bower install angularLocalStorage
```

So I'm not sure if removing ngStorage from the bower registry would be a breaking change. I know everyone there is busy, but this is a real drag for people who wish to use the ngStorage module, and have to find out the hard way that they didn't install the module they intended to install.

Hope there is something that can be done.

**Comment by sheerun** [comment]
Sorry, we can't do much about it. Users already can depend on these packages.
