### ISSUE TITLE
Allow unregistering any package using emailed one time token

### ISSUE THREAD

**Issue by herby** [bower/registry#136]
Allow to unregister any package by adding an option to email a one-time short-lived token to author(s) mentioned in package's bower.json, which they can use in existing CLI,

That is, check the token not only against github oauth, but also against some temporary store (an in-memory bounded-size queue) of [token, project] pairs..

**Comment by BenMann** [comment]
Pretty much same as https://github.com/bower/bower/issues/2167 & ooold.
Closing.
