### ISSUE TITLE
Please unregister "jquery-countTo"

### ISSUE THREAD

**Issue by mhuggins** [bower/registry#137]
Hi there,

I have a package named [jquery-countTo](https://github.com/mhuggins/jquery-countTo).  Unfortunately someone forked my repo and took the name by pointing bower to their fork before I could register.  They've since deleted their fork (git://github.com/Atolye15-packs/jquery-countTo.git).  Since their fork is deleted, is it possible to unregister their stolen name so that I can correctly point it to my repo?  This is leading to issues for users [as seen here](https://github.com/mhuggins/jquery-countTo/issues/43).

**Comment by desandro** [comment]
Re-registered to `jquery-countTo` to `git://github.com/mhuggins/jquery-countTo.git`

Thanks for using Bower!

**Comment by mhuggins** [comment]
Awesome, thanks so much!
