### ISSUE TITLE
Login with GitHub tokens

### ISSUE THREAD

**Issue by nkbt** [bower/registry#138]
I don't really want to use my GitHub account password. And I have 2-factor auth anyway. It seems like bower does not support token authentication at the moment at all.

<img width="717" alt="20150718-174147" src="https://cloud.githubusercontent.com/assets/175264/8760823/ba9a202a-2d74-11e5-9f4e-24b3ff325278.png">

**Comment by sheerun** [comment]
You can provide `--token` option if you don't want to type your password.

Bower supports 2-factor auth.
