### ISSUE TITLE
Unregister bespoke-theme-fancy

### ISSUE THREAD

**Issue by fegemo** [bower/registry#139]
Hi,

I'd like to know if you can unregister the bespoke-theme-fancy package for me.
I actually registered it with a wrong repo URL ('https://github.com/markdalgleish/generator-bespokeplugin'), but it should have been https://github.com/fegemo/bespoke-theme-fancy.git.

If I try to unregister the package, I get bower EFORBIDDEN    Must have push access to view repository collaborators.

Thanks and sorry for the inconvenience.

**Comment by desandro** [comment]
@markdalgleish Do we have your permission to unregister `bespoke-theme-fancy`?

**Comment by markdalgleish** [comment]
Just unregistered it for you.

**Comment by fegemo** [comment]
Thanks, Mark. Sorry for the trouble :smile:
