### ISSUE TITLE
Supporting plugin ecosystems

### ISSUE THREAD

**Issue by jugglinmike** [bower/registry#14]
I'm interested in using a package manager to foster an ecosystem of plugins for my open source library. The Bower registry already allows me to filter for packages that are named appropriately (e.g. `grunt-` for Grunt plugins). An additional use case that is not served by project namespacing is versioning. I would like developers to be able to quickly filter out plugins that are incompatible with the version of the library they're using.

If the registry exposed the `peerDependency` information specified in projects' `package.json` files, then the registry could be queried much more efficiently. Would this behavior be considered in-scope for Bower?

**Comment by sheerun** [comment]
Supporting plugin ecosystems has nothing to do with embedding peerDependencies in api responses.

And peer-dependencies don't make much sense for bower, because all dependencies are flattened.
