### ISSUE TITLE
Cannot unregister package

### ISSUE THREAD

**Issue by tgelu** [bower/registry#140]
This is most likely an enhancement because it took me some time to figure out the solution to the following:
I have registered a package and after some time I have decided to delete the repo on github but forgot to unregister the package from bower.
When I decided to do that also I got 
``` bower EFORBIDDEN    Must be a collaborator on GitHub.com repository ```
which confused me for a while until I remembered to check if the repository exists, then create an empty one with the same name, then unregister the bower package and then delete the newly created repo.

Maybe a more detailed error message will help others :)

**Comment by desandro** [comment]
Yes, this is a weird edge case. Typically, we ask that you submit a new issue so that I can manually delete the package in the registry. Your solution works just as well. Thanks for reporting it! :whale:

**Comment by rahilwazir** [comment]
@tgelu Thanks for solution

**Comment by pertrai1** [comment]
@desandro Is this issue ready to be closed?
