### ISSUE TITLE
Dragula returns 404, can we replace it?

### ISSUE THREAD

**Issue by bevacqua** [bower/registry#143]
Hey there. There's a `dragula` package that points to a 404 on GitHub at [github.com/skyGoWeb/dragula](https://github.com/skyGoWeb/dragula).

Can we register [`dragula`](https://github.com/bevacqua/dragula) there?

Many thanks

**Comment by sheerun** [comment]
Please contact skyGoWeb to unregister it from bower

**Comment by bevacqua** [comment]
They don't even exist on github anymore. That's the point.

On Thursday, August 13, 2015, Adam Stankiewicz <notifications@github.com>
wrote:

> Please contact skyGoWeb to unregister it from bower
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bower/registry/issues/143#issuecomment-130732520>.
>


-- 


github <https://github.com/bevacqua> · blog <http://ponyfoo.com/> · twitter
<https://twitter.com/nzgb> · book <http://bevacqua.io/buildfirst> · career
<http://careers.stackoverflow.com/bevacqua> ·about <http://bevacqua.io/>

**Comment by desandro** [comment]
[skyGoWeb/dragula](https://github.com/skyGoWeb/dragula) no longer exists, nor does the user @skyGoWeb. I feel good doing a re-register.

Re-registered `dragula` to `git://github.com/bevacqua/dragula.git`.

**Comment by bevacqua** [comment]
Woo! Many thanks!
