### ISSUE TITLE
Turbolinks package source repo has been deleted

### ISSUE THREAD

**Issue by schneidmaster** [bower/registry#145]
The source repo for the [Turbolinks](https://libraries.io/bower/turbolinks) package has been deleted. It appears that the former maintainer (@menglr) has entirely deleted their GitHub account.

I have created a substitute shim at rails-turbolinks. Would it be possible to reclaim the original turbolinks package name? If so, I am willing to maintain the updated package. Presently `bower install turbolinks` just fails with a message that the source repo doesn't exist.

**Comment by desandro** [comment]
`turbolinks` has been unregistered. Any way you can add Bower support to the primary [rails/turbolinks](https://github.com/rails/turbolinks) repo?

**Comment by schneidmaster** [comment]
Thanks. I am not a maintainer there but I will send them a PR and see if they will add it.
