### ISSUE TITLE
"bower unregister" -> feature or bug?

### ISSUE THREAD

**Issue by leolux** [bower/registry#146]
Nothing seems to work at the moment:

```
$ curl -X DELETE "https://bower.herokuapp.com/packages/exports-boilerplate?access_token=xxxx"
Must be a collaborator on GitHub.com repository
```

```
$ bower unregister exports-boilerplate
bower EFORBIDDEN    Use "bower login" with collaborator credentials
```

"bower login" wants my git credentials?? No!

I am using bower version 1.5.2. How to delete a package with this?

**Comment by leolux** [comment]
My access token is limited to the following scope:
repo, repo:status and user

Is there anything missing?

**Comment by sheerun** [comment]
exports-boilerplate is registered to github.com/leolux/exports-boiplerplate and it doesn't exist ;/ You need to create this repository, remove package from bower, and remove repository

**Comment by leolux** [comment]
Alright, thanks! 
So I would suggest to add this to the error message "The repository needs to exist in order for the unregistration to work"

**Comment by sheerun** [comment]
Yeah ;/ We need to improve it. I'll add an issue
