### ISSUE TITLE
angular-drupal name transfer

### ISSUE THREAD

**Issue by signalpoint** [bower/registry#148]
Hello Bower Team,

I've created this repository:

https://github.com/easystreet3/angular-drupal

And have registered it on npmjs.org:

https://www.npmjs.com/package/angular-drupal

I tried registering it on bower.io, but got this error:

```
bower                       EDUPLICATE Duplicate package
```

I then contacted the author who previously registered that namespace with their project https://github.com/alexpsi/ng-drupal, and have since resolved the issue with them here: https://github.com/alexpsi/ng-drupal/issues/1

I now am trying to register it again, but am receiving the same duplicate package error mentioned above. The original author unregistered it (AFAIK) about 30 minutes ago, so perhaps caching is causing an issue. Please advise, thank you!

**Comment by desandro** [comment]
+ Un-registered `angular-drupal`
+ Registerd `angular-drupal` to `git://github.com/easystreet3/angular-drupal.git`

`ng-drupal` is registered to a different package, so I couldn't register `github.com/alexpsi/ng-drupal` to it. @alexpsi
