### ISSUE TITLE
Unregister package maetrial-analytics

### ISSUE THREAD

**Issue by prabinv** [bower/registry#151]
I published the package with a typo in the name - `maetrial-analytics`. I have since created a new package with the correct spelling. Can you please unregister this one?

**Comment by desandro** [comment]
Have you tried unregistering it yourself? http://bower.io/docs/creating-packages/#unregister

**Comment by prabinv** [comment]
@desandro I did try doing that, but `bower login` supports only basic auth. And my github is set up with 2 factor auth (company policy). Any way to get around this other than to turn off 2 factor auth?

**Comment by desandro** [comment]
Unregistered `maetrial-analytics`
