### ISSUE TITLE
unregister arrowjs

### ISSUE THREAD

**Issue by pbojinov** [bower/registry#152]
[https://github.com/pbojinov/arrow-js](arrowjs) was on an organization that I was apart of but now does not exist, so the package is stuck in limbo. Bower currently points to this broken link - `git://github.com/ConduitInc/ArrowJS.git`

When I try to unregister it gives me a `bower EFORBIDDEN    Must be a collaborator on GitHub.com repository` since the organization 404s

Can you please unregister?

**Comment by desandro** [comment]
Looks like this has been resolved. 

``` bash
$ bower lookup arrow-js
# arrow-js git://github.com/pbojinov/arrow-js.git
```

**Comment by pbojinov** [comment]
@desandro you're right, `arrow-js` is resolved but there's the remnant of the old project still here:

```
> bower lookup arrowjs
arrowjs git://github.com/ConduitInc/ArrowJS.git
```

Is there a way I can remove that?

**Comment by desandro** [comment]
unregistered `arrowjs`

**Comment by pbojinov** [comment]
thank you :+1:
