### ISSUE TITLE
[DISPUTE] I am the true owner of FuckAdBlock

### ISSUE THREAD

**Issue by sitexw** [bower/registry#154]
Hello, I come to you because I noticed about Bower, the name "fuckadblock" is already used by another. It is to point on an obsolete fork (http://github.com/tchakabam/FuckAdBlock) of my script "FuckAdBlock" (https://github.com/sitexw/FuckAdBlock).
I tried to contact the person, but I have not succeeded.

I am working on my script V4 and I would like for the occasion to be available on Bower with the name "fuckadblock". Because at the moment I use "fuck-adblock" but I can not find it to adapt and we do not find myself in search of Bower.

Thank you for your attention.

**Comment by desandro** [comment]
@tchakabam I'd like to unregister `fuckadblock` so it can be registered to @sitexw's repo. Looks like your fork is a couple years behind. I'll give you 5 days to respond. Otherwise, I'll unregister it on November 10th.

**Comment by sitexw** [comment]
Thanks for your feedback.

Ps: I had not thought to put their username in the message so that it receives mail.

**Comment by tchakabam** [comment]
hey @sitexw, i am on github everyday so it should not be hard to contact me via the issue tracker of the repo you mention :)

i had packaged your stuff for bower back in days in the first place and proposed you to take ownership of it - i think you were happy it was being distributed that way but didn't take any further steps. the reason i did this back in the day was simply to be able to use it in our asset pipeline back in the days and to share that possibility with you and others.

i have no problem at all with you taking over maintenance of this bower package at all. but your dispute here seems a bit rough. but fuck it, at least now you know how to contact people on github ;)

**Comment by desandro** [comment]
@tchakabam Thank you for your understanding. My apologies for being curt.

I've registered `fuckadblock` to `git://github.com/sitexw/FuckAdBlock.git`

**Comment by sitexw** [comment]
Really sorry for this "dispute" but I really did not think to put your nickname in my message. And I should have simply created an issue on my project. For a next time!

Anyway, thank you for what you work you have done beginning of FuckAdBlock and thank you for being for me to take over the namespace on Bower.

@desandro Thanks to you too.
