### ISSUE TITLE
Accidentally register wrong git-endpoint and cannot remove package

### ISSUE THREAD

**Issue by boogiebug** [bower/registry#157]
I've accidentally register a package with wrong git endpoint. When I tried to unregister it, I got the following error. How could I unregister this invalid package, please suggest.

Package Name: chartist-plugin-legend
the "incorrect" endpoint is: https://github.com/bower/bower

Error Message when unregister:
bower EFORBIDDEN    Must have push access to view repository collaborators.

**Comment by boogiebug** [comment]
PS: I've already successfully done the 'bower login'.

**Comment by desandro** [comment]
Unregistered `chartist-plugin-legend` :heavy_multiplication_x: 

Thanks for using Bower :bird:

**Comment by dotnetCarpenter** [comment]
@desandro I have a similar issue. I'm trying to re-register svg.js to update our new URL (git@github.com:svgdotjs/svg.js.git). But I'm getting the same error.
`bower EFORBIDDEN    Must have push access to view repository collaborators.`

How do I work around this?

**Comment by desandro** [comment]
@dotnetCarpenter sorry, I don't have access to make this change any more. Please open a new issue so the team can track your request.
