### ISSUE TITLE
Unregister http.js

### ISSUE THREAD

**Issue by alfredxing** [bower/registry#158]
There's currently a project under the name `http.js` for which the linked repository no longer exists.

I realize that in #115 that there was some discussion about attackers potentially installing malicious code and whatnot, but I think this can still be done on a case-by-case basis.

The project I'd like to put under that name would be [wylst/http.js](https://github.com/wylst/http.js) (which you can see is not malicious in any form).

Thanks!

**Comment by desandro** [comment]
`http.js` has been un-registered. Thank you for using Bower :bird:

**Comment by alfredxing** [comment]
Thanks!
