### ISSUE TITLE
Update cloud9carousel

### ISSUE THREAD

**Issue by specious** [bower/registry#159]
Right now `cloud9carousel` points to `git://github.com/qdubious/cloud9carousel.git`, however that is a fork of my upstream project, which is significantly more up to date.  I would like to change it to `git@github.com:specious/cloud9carousel.git`.

**Comment by desandro** [comment]
@qdubious — Hello! We'd like to re-register `cloud9carousel` from your fork, to the original [specious/cloud9carousel](https://github.com/specious/cloud9carousel). Is this alright?

If we don't hear back in 7 days, we'll move forward with the re-register

**Comment by desandro** [comment]
`cloud9carousel` re-registered to `git://github.com/specious/cloud9carousel.git`. Thank you for using Bower :bird:
