### ISSUE TITLE
Unregister request: package "mana" has nonexistent git endpoint

### ISSUE THREAD

**Issue by andrewgioia** [bower/registry#162]
Hi all, I tried registering [my project](https://github.com/andrewgioia/Mana) under the name "mana" but it looks like that bower package is already registered:

    "name": "mana",
    "url" : "git://github.com/volkovasystems/inherits.git",
    "hits": 0

That git repository no longer exists and the owner has not responded to my email asking if I could take over the bower package name. Is it possible for someone to manually unregister it for me?

Thank you and if this is the wrong place, please let me know. An [older issue](https://github.com/bower/registry/issues/111) pointed to one that has since been closed for these requests.

**Comment by desandro** [comment]
`mana` has been unregistered :heavy_multiplication_x: All yours. Thank you for using Bower :bird:

**Comment by andrewgioia** [comment]
Awesome, thank you!

**Comment by Kimoja** [comment]
Hi, i have the same probleme with my project https://github.com/Kimoja/jstroll
Can you help me andrewgioia ? 
Thank you !
