### ISSUE TITLE
bower EAUTH Bad credentials

### ISSUE THREAD

**Issue by widoz** [bower/registry#164]
No way to login

I followed the http://bower.io/docs/creating-packages/#register instructions to unregister a package.

```
bower login
# enter username and password
? Username:
? Password:
# unregister packages after successful login
bower unregister <package>
```

But I'm not able to login.

**Comment by rajzshkr** [comment]
@widoz what you are trying to do?  If bower login is not working then check whether you using the right credentials. It works for me !!

**Comment by widoz** [comment]
@rajzshkr Yup I used the correct github credentials.

**Comment by ceoaliongroo** [comment]
@widoz, please try again.

I closed the issue, because also i tested and works fine.

__Tested with right credentials and then wrong credentials__
```bash 
172-15-13-240:ionic carlosmantilla$ bower login
? Username ceoaliongroo
? Password *********
172-15-13-240:ionic carlosmantilla$ bower login
? Username ceoaliongroo
? Password ******
bower EAUTH         Bad credentials
```
