### ISSUE TITLE
Please unregister 'minitypeahead'. Code moved to github :)

### ISSUE THREAD

**Issue by wampiedriessen** [bower/registry#167]
Please let me know if I have to register it again myself, this time using github.
old repo: git://bitbucket.org/wampiedriessen/minitypeahead.git
new repo: git://github.com/wampiedriessen/minitypeahead.git

**Comment by desandro** [comment]
:arrow_right:  Re-registered `minitypeahead` to `git://github.com/wampiedriessen/minitypeahead.git`

Thank you for using Bower :bird:
