### ISSUE TITLE
Unregister and re-register jquery.event.drag-drop

### ISSUE THREAD

**Issue by nathell** [bower/registry#168]
Please change the package `jquery.event.drag-drop` as per https://github.com/bower/bower/issues/1705.

I am unable to do this myself because I hadn't been a collaborator of the original GitHub repo (which no longer exists). This package is important as it's a dependency, _inter alia_, of slickgrid.

**Comment by desandro** [comment]
I've unregistered `jquery.event.drag-drop`. You can re-register it where you feel appropriate. Looks like [dextermilo/jquery.threedubmedia](https://github.com/dextermilo/jquery.threedubmedia) is no longer available.
