### ISSUE TITLE
Reregister simple-ajax-uploader

### ISSUE THREAD

**Issue by enumag** [bower/registry#169]
The package simple-ajax-uploader points to a [fork](https://github.com/jenkinliang/Simple-Ajax-Uploader) instead of the [original](https://github.com/LPology/Simple-Ajax-Uploader) package. We ware unable to contact the owner of the fork @jenkinliang.

Can you unregister or reregister the package so that the maintainer @LPology can manage it?

Ref https://github.com/LPology/Simple-Ajax-Uploader/issues/138

**Comment by desandro** [comment]
:left_right_arrow:  Re-registered `simple-ajax-uploader` to `git://github.com/LPology/Simple-Ajax-Uploader.git`

Thank you for using bower! :bird:

**Comment by enumag** [comment]
@desandro Is there some delay involved? Bower search still links to the fork. http://bower.io/search/?q=simple-ajax-uploader

**Comment by desandro** [comment]
Search takes a while. If you clear your cache and try `bower lookup simple-ajax-uploader` it'll be there.

**Comment by enumag** [comment]
Ok, thank you!
