### ISSUE TITLE
Unable to unregister packages that were registered with wrong git-endpoint

### ISSUE THREAD

**Issue by hatra-e** [bower/registry#171]
Hi,

I just registered 14 packages and made the mistake of using the normal GitHub URL like this:
`https://github.com/revolt-framework/base.figure`
instead of the correct git-endpoint like this:
`git://github.com/revolt-framework/base.figure.git`
in the register dialog.

I wanted to correct my error by unregistering the packages and then registering them again with the correct git-endpoint, but I am getting the following error message:

`bower EUNKNOWN      Unknown error: 503 - <!DOCTYPE html>     <html>     <head>       <meta name="viewport" content="width=device-width, initial-scale=1">       <style type="text/css">         html, body, iframe { margin: 0; padding: 0; height: 100%; }         iframe { display: block; width: 100%; border: none; }       </style>     <title>Application Error</title>     </head>     <body>       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">         <p>Application Error</p>       </iframe>     </body>     </html>
`

Is it possible that an admin can delete the following packages manually or give me instructions on how to unregister them correctly?

`revolt.settings.defaults`
`revolt.tools.functions`
`revolt.generic.normalize`
`revolt.generic.reset`
`revolt.generic.box-sizing`
`revolt.generic.vertical-spacing`
`revolt.base.root`
`revolt.base.figure`
`revolt.base.hr`
`revolt.base.lists`
`revolt.base.responsive-images`
`revolt.objects.list-bare`
`revolt.objects.list-inline`
`revolt.objects.media`

Thanks!

**Comment by hatra-e** [comment]
Nevermind about deleting the packages. I just looked into http://bower.herokuapp.com/packages and it looks like the URLs got converted into the correct git-entpoints. 

However, it's weird that I am unable to unregister any of the packages.

**Comment by BenMann** [comment]
Hmm, looks like you're onto something here.
I'll close in favor of https://github.com/bower/bower/issues/2171 (same problem - unregistering)
