### ISSUE TITLE
Unregistering yields "Application Error"

### ISSUE THREAD

**Issue by Garciat** [bower/registry#173]
![image](https://cloud.githubusercontent.com/assets/118277/13024313/32c54dd8-d1c9-11e5-9a0e-e11392fe61d1.png)

Also:

```
~$ curl -X DELETE "https://bower.herokuapp.com/packages/libvorbis.js?access_token=MY_TOKEN"
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

My particular case:

I renamed my repo from `Garciat/libvorbis.js-bower` to `Garciat/libvorbis.js-dist`. I want to unregister the package and re-register it with the new repo URI.

**Comment by BenMann** [comment]
Thanks for letting us know.
There is a known issue with unregistering packages at the moment.
I'll close in favor of https://github.com/bower/bower/issues/2171. Unregistering should work again, when this is solved.

**Comment by BenMann** [comment]
You should now be able to unregister packages as intended. :tada:
