### ISSUE TITLE
unregister ormico-first-bowerpkg

### ISSUE THREAD

**Issue by ormico** [bower/registry#174]
please unregister package ormico-first-bowerpkg.
i am receiving this error
EUNKNOWN      Can only unregister packages hosted on GitHub.com
package is hosted at bitbucket.org
i wanted to test hosting at bitbucket and then remove the package, but cannot remove.

**Comment by desandro** [comment]
Unregistered `ormico-first-bowerpkg`. Thank you for using Bower :bird:
