### ISSUE TITLE
Package `nifty-nav` not showing in registry

### ISSUE THREAD

**Issue by erwstout** [bower/registry#177]
We have a package called `nifty-nav` that doesn't appear in the search registry. Any thoughts?

Our `bower.json`:

```json
{
  "name": "nifty-nav",
  "description": "Nifty Nav is a quick and easy navigation plugin using Sass and jQuery. It makes making navigation systems a little better.",
  "main": "nifty-nav.js",
  "authors": [
    "Eric Stout / Factor1 <eric@factor1studios.com>"
  ],
  "license": "MIT",
  "keywords": [
    "Navigation",
    "Mobile",
    "Navigation",
    "Nav",
    "Mobile",
    "Nav",
    "Nifty",
    "Nav",
    "factor1"
  ],
  "homepage": "https://github.com/factor1/nifty-nav",
  "moduleType": [],
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}
```

It does appear when searching via command line:

```
bower search nifty-nav
Search results:

nifty-nav git://github.com/factor1/nifty-nav.git
```

Thanks!

**Comment by desandro** [comment]
It takes a day or so for results to show up in the search. Sit tight.

**Comment by samccone** [comment]
**TIL**

> To "sit tight" means to not take any further action until you are told to do so. In other words, to wait. There's a bit of a question as to the origin of this idiom. The tight aspect of this idiom, most likely, comes from when it was common in the Western world to have a bed frame made of ropes strung equally apart both horizontally and vertically in the frame. One would tighten the ropes before getting into bed to assure the mattress laid on the ropes as straight as possible. Through the evening of sleeping on the ropes, they would gradually loosen. A good night's sleep would be if your ropes stayed tight so you had a nice, firm surface to sleep on all night.

**Comment by erwstout** [comment]
@desandro it's been weeks, unfortunately.

**Comment by desandro** [comment]
Hmm, sorry about that. Closing here, moving to bower/search#86
