### ISSUE TITLE
Made a mistake when registering new module

### ISSUE THREAD

**Issue by hippich** [bower/registry#178]
Pointed requirejs-svg to requirejs-text plugin (https://github.com/requirejs/text), instead of requirejs-svg (https://github.com/hippich/requirejs-svg)

Now it appears I can't unregister it, since it was pointed to repo I have no access to.. Could you guys help either re-point it to proper repo or  unregister it, so I could repeat it with proper URL?

**Comment by desandro** [comment]
`requirejs-svg` has been unregistered :heavy_multiplication_x: Thank you for using Bower :bird:
