### ISSUE TITLE
Move angular-ui-router to new repo

### ISSUE THREAD

**Issue by christopherthielen** [bower/registry#179]
Please move bower package "angular-ui-router"

From: https://github.com/angular-ui/ui-router
To: https://github.com/angular-ui/angular-ui-router-bower

**Comment by desandro** [comment]
`angular-ui-router` has been unregistered :heavy_multiplication_x: . Once you have created `bower.json` on the new repo you can re-register it.

```
bower register angular-ui-router git://github.com/angular-ui/angular-ui-router-bower.git

**Comment by christopherthielen** [comment]
Thanks.  I created `bower.json` in the `master` branch (using the bower.json from the latest release), then ran `bower register angular-ui-router git://github.com/angular-ui/angular-ui-router-bower.git`

https://github.com/angular-ui/ui-router/issues/2592

This is a pretty high traffic project.  Can this transfer happen atomically?
