### ISSUE TITLE
please unregister mathquill-dist

### ISSUE THREAD

**Issue by Draccoz** [bower/registry#180]
I am still a beginner in bower publishing and I registered a package (`mathquill-dist`) without forking it (was hoping I just register build files). Now, the `mathquill` project has no dist files (need to build it), and I cannot unregister the package because I have no access to their repo. Could that be fixed please?

**Comment by desandro** [comment]
`mathquill-dist` has been unregistered.

**Comment by Draccoz** [comment]
Thank you :).
