### ISSUE TITLE
Unregister unofficial jquery-csv fork

### ISSUE THREAD

**Issue by evanplaice** [bower/registry#181]
A while back when jquery-csv was still hosted on Google Code a particularly impatient dev forked the project, published it on GitHub, and registered a now deprecated version on Bower.io.

Development on the fork died after a handful of commits and the useful changes were merged back into the official repo. Since then, the main repo has been migrated to GitHub and development has continued to progress.

Unfortunately, since the lib already has an entry in the Bower registry that was added by somebody other than myself, I am unable to update the registry with the latest. I have attempted to reacy out to get the other dev to update bower with no response.

Is there any way I can take ownership of the registration of jquery-csv? The project is gradually regaining in popularity since the migration and users are wondering why it isn't available on Bower.

Ref: https://github.com/evanplaice/jquery-csv/issues/56

**Comment by desandro** [comment]
The simplest solution is to register it with another name. `jq-csv` is available. Is this suitable?

**Comment by evanplaice** [comment]
@desandro Not really, no. The name is ubiquitous. The project already has a 5+ year history. It's already registered on NPM and will soon be added to the JSPM registry. Using a different name exclusively for Bower would just confuse users.

Thanks for the quick response

**Comment by desandro** [comment]
@mirlord Do you have any objection to re-registering `jquery-csv` to the original repo? If we don't hear back from you in ~5 days, I'll make the switch.

**Comment by desandro** [comment]
`jquery-csv` has been re-registered to `git://github.com/evanplaice/jquery-csv.git`. Thank you for using Bower :bird:
