### ISSUE TITLE
Unregister Request: bootstrap-grid 

### ISSUE THREAD

**Issue by jrummell** [bower/registry#183]
Hi, I'm trying to register a new package with a name not found on [bower search](http://bower.io/search/?q=bootstrap-grid). I used to the `bower info` command to see that there is a registered repository with that name, but it does not exist. Can you please free that up for me?

    > bower register bootstrap-grid https://github.com/jrummell/bootstrap-grid.git
    bower bootstrap-grid#*         resolve https://github.com/jrummell/bootstrap-grid.git#*
    bower bootstrap-grid#*        checkout master
    bower bootstrap-grid#*    invalid-meta bootstrap-grid is missing "main" entry in bower.json
    bower bootstrap-grid#*        resolved https://github.com/jrummell/bootstrap-grid.git#985f8340e5
    ? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
    bower bootstrap-grid          register https://github.com/jrummell/bootstrap-grid.git
    bower                       EDUPLICATE Duplicate package

    > bower info bootstrap-grid
    bower bootstrap-grid#*      not-cached git://github.com/shoehorn/grid.git#*
    bower bootstrap-grid#*         resolve git://github.com/shoehorn/grid.git#*
    bower                          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/shoehorn/grid.git", exit code of #128 fatal: remote error:    Repository not found.

    Additional error details:
    fatal: remote error:
      Repository not found.

**Comment by desandro** [comment]
`bootstrap-grid` has been unregistered. Thank you for using Bower.

**Comment by jrummell** [comment]
Thanks!
