### ISSUE TITLE
Transfer ownership of angular-imgcache.js

### ISSUE THREAD

**Issue by Maistho** [bower/registry#184]
Hello,

It seems that I am the new maintainer of angular-imgcache.js. The old repo isn't working, and JBenes is very unresponsive, although said that he/she would work to transfer the repo. (jBenes/angular-imgcache.js#19)

Since I've also gotten chrisbens imgcache.js to point to my fork, it would be nice to have the bower name so that can be updated to the working version as well.
Is it possible to transfer the package to me, and set the repository to https://github.com/maistho/angular-imgcache.js ?

**Comment by desandro** [comment]
Looks like @JBenes has given consent in https://github.com/jBenes/angular-imgcache.js/issues/19#issuecomment-188777581

`angular-imgcache.js` has been re-registered to `git://github.com/Maistho/angular-imgcache.js.git`. Thank you for using Bower :bird:
