### ISSUE TITLE
Register warpwallet-dismantled

### ISSUE THREAD

**Issue by davidapple** [bower/registry#185]
Can you please register 'warpwallet-dismantled' to github.com/davidapple/warpwallet-dismantled/

Bower currently informs me that it's already registered but it doesn't show up in the search.

**Comment by sheerun** [comment]
you need to wait for search to catch up with registry

**Comment by davidapple** [comment]
Thanks sheerun. How long does it normally take?

**Comment by sheerun** [comment]
1 day max

**Comment by davidapple** [comment]
Sorry, it's still not showing in the search http://bower.io/search/?q=warpwallet

**Comment by davidapple** [comment]
Please help
