### ISSUE TITLE
Re-register jquery-oembed-all

### ISSUE THREAD

**Issue by dt1973** [bower/registry#186]
Hi!

https://github.com/nfl/jquery-oembed-all/ was recently added but with an incorrect semver tag. This has since been fixed, so would anyone mind re-registering this package?

Thanks!

**Comment by desandro** [comment]
I don't believe re-registering the package will fix this issue. A valid semver would be `0.0.9-rc1` or `0.9.0-rc1`. If you push one of these valid tags, Bower will automatically add it to its available versions.

**Comment by dt1973** [comment]
Great news, thanks a lot @desandro!
