### ISSUE TITLE
Accidentally registered package as private

### ISSUE THREAD

**Issue by mike-shtil** [bower/registry#190]
Hi,

I accidentally initially registered the package "grd" (https://github.com/mike-shtil/grd) as private. To make it public, I attempted to unregister it (after a successful bower login with a generated token).

However, I get this error: Must have push access to view repository collaborators. This while my user is the repository's owner.

I attempted the curl command as well, with the same error.

How can I go about unregistering the package to re-register it as public? Thanks!

**Comment by desandro** [comment]
Looks like `grd` is registered to https://github.com/1000ch/grd , so you wouldn't have access to un-register it. I recommend registering your package under a different name.

**Comment by mike-shtil** [comment]
Thanks for that bit of info!
