### ISSUE TITLE
Trouble unregistering a repostory that changed GH owner.

### ISSUE THREAD

**Issue by pygy** [bower/registry#191]
Hello,

I've transferred the owership of a library I was managing back to its original author, and it seems that the easiest way to transfer the Bower account would be to unregister/register it back in a coördinated fashion.

The trouble is, I can't remember my Bower credentials, and the cURL method doesn't work either.

Using `bower install` still works after the GitHub transfer, but this occurs:

```
$ curl -X DELETE "https://bower.herokuapp.com/packages/underscore-deep-extend??access_token=A_VALID_TOKEN_FRESHLY_GENERATED"
Must be a collaborator on GitHub.com repository
```

The old URL is https://github.com/pygy/underscoreDeepExtend, which now redirects to https://github.com/kurtmilam/underscoreDeepExtend

I'm still a collaborator after the transfer, so there's likely a bug on your end.

I've seen you could unregister packages on request, if you were to do it, it would be nice to do it in sync with @kurtmilam so that someone doesn't steal the name in the mean time.

We've been discussing the transfer here: https://github.com/kurtmilam/underscoreDeepExtend/issues/14#issuecomment-209090679

Thanks in advance for the help :-)

**Comment by desandro** [comment]
`bower info underscore-deep-extend` points to `https://github.com/kurtmilam/underscoreDeepExtend.git`. Looks like you've already managed to properly register this to the new owner

**Comment by pygy** [comment]
> `bower info underscore-deep-extend` points to `https://github.com/kurtmilam/underscoreDeepExtend.git`. Looks like you've already managed to properly register this to the new owner

Great news!

cc/ @kurtmilam
