### ISSUE TITLE
Regaining control of project name

### ISSUE THREAD

**Issue by Anthropic** [bower/registry#192]
Greetings @desandro and anyone else from @bower/registry,
I created [**angular-schema-form-material**](https://github.com/json-schema-form/angular-schema-form-material) and was [notified](https://github.com/json-schema-form/angular-schema-form-material/issues/16) before the project was completed for alpha that my repo was copied with a different name (**schemaform-material**), but then submitted to Bower under the name of my repo.

I have logged an issue with them https://github.com/nick121212/schemaform-material/issues/2, but have not heard anything back yet so I thought I should raise it here to get a quick resolution.

You can see from the commit history that they are nearly all mine: https://github.com/nick121212/schemaform-material/commits/develop

I am now managing the entire https://github.com/json-schema-form organisation responsible for the project now, which led to some delay, so I suspect it was not malicious, more impatient, but I was hoping someone at Bower could help me please.

Regards,
Marcel

**Comment by desandro** [comment]
Looks like both `schemaform-material` and `angular-schema-form-material` are available to be registered. Has this already been resolved?

**Comment by Anthropic** [comment]
I just got a response, I wasn't sure what it meant till now, so I guess it is, yes, thank you!

**Comment by Anthropic** [comment]
Actually @desandro I'm not at my computer for another 8 hours as I'm in bed and it's midnight in Australia, any way to stop someone grabbing it overnight however unlikely that is?

**Comment by juanmav** [comment]
Sorry for the intrusion, but I did that for you. :P

```console
Now using node v5.10.1 (npm v3.8.3)
juanmav@juanmav:~$ bower register angular-schema-form-material https://github.com/json-schema-form/angular-schema-form-material.git
bower resolve       https://github.com/json-schema-form/angular-schema-form-material.git#*
bower checkout      angular-schema-form-material#master
bower resolved      https://github.com/json-schema-form/angular-schema-form-material.git#52a3011539
? Registering a package will make it installable via the registry (https://bower? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower register      https://github.com/json-schema-form/angular-schema-form-material.git

Package angular-schema-form-material registered successfully!
All valid semver tags on https://github.com/json-schema-form/angular-schema-form-material.git will be available as versions.
To publish a new version, just release a valid semver tag.

Run bower info angular-schema-form-material to list the available versions.
```

Regards
JM
