### ISSUE TITLE
Request: Url migration git => https

### ISSUE THREAD

**Issue by herby** [bower/registry#193]
Hello, as https://github.com/bower/bower/issues/1841 was closed and https is now preferred over git, could I please ask to change all entries with url `git://lolg.it/...` to use https instead? I myself cannot do it, as they are not unregistrable, being non-github. Thanks.

P.S.: If possible, also add final `.git` to 'helios' package, as I forgot to specify it (all others do have it).

**Comment by BenMann** [comment]
Closing in favor of  https://github.com/bower/bower/issues/2292

**Comment by herby** [comment]
Pls reopen, the linked issue is about bower feature request, not about manual fixing of registry entries, of which this request is. Thanks.

Affected packages are ones found by `bower search lolg.it`. I don't want them unregistered as they will becone unavailable until I reregister them, but onlt fix protocol to https, of possible. If only unregistering is possible, then I would like it to happen when I am actually online.

Dňa 10. júna 2016 10:35:34 CEST používateľ Ben <notifications@github.com> napísal:

**Comment by herby** [comment]
To be precise, the list of packages involved is:
```
    lyst git://lolg.it/herby/lyst.git
    amber-compat-ie8 git://lolg.it/amber/amber-compat-ie8.git
    amber-contrib-legacy git://lolg.it/amber/amber-contrib-legacy.git
    amber-contrib-web git://lolg.it/amber/amber-contrib-web.git
    amber-compat-es5 git://lolg.it/amber/amber-compat-es5.git
    amber-compat-es2015 git://lolg.it/amber/amber-compat-es2015.git
    domuri git://lolg.it/herby/domuri.git
    xontent git://lolg.it/herby/xontent.git
    hqueue git://lolg.it/herby/queue.git
    updchg git://lolg.it/herby/updchg.git
    usim git://lolg.it/herby/usim.git
    repre git://lolg.it/herby/repre.git
    requirejs-promised git://lolg.it/herby/requirejs-promised.git
    trapped git://lolg.it/herby/trapped.git
    amber git://lolg.it/amber/amber.git
    sedux git://lolg.it/herby/sedux.git
    helios git://lolg.it/amber/helios
    amber-contrib-jquery git://lolg.it/amber/amber-contrib-jquery.git
```

**Comment by herby** [comment]
Thanks. If fixing is not possible but unregistering is, I am online now, so if you could do it now, it will have lesser downtime (ignore if you're not online now). Thanks.

Adam Stankiewicz wrote:

**Comment by sheerun** [comment]
I'm going to do it right now

**Comment by herby** [comment]
Thanks.

Adam Stankiewicz wrote:

**Comment by sheerun** [comment]
@herby All urls should be migrated now, could you check?

**Comment by herby** [comment]
Yes, they are; thank you, sir.
