### ISSUE TITLE
Please change des-responsive-framework, des-deakinsync-framework and des-base-framework URLs

### ISSUE THREAD

**Issue by timrandall** [bower/registry#195]
Hello,

I would like to request that the URLs for the following packages be updated as follows:

1. des-responsive-framework: new URL - https://stash.deakin.edu.au/projects/FRAMEWORK/repos/framework-responsive/
2. des-base-framework: new URL - https://stash.deakin.edu.au/projects/FRAMEWORK/repos/framework-base/
3. des-deakinsync-framework: new URL - https://stash.deakin.edu.au/projects/FRAMEWORK/repos/framework-deakinsync/

Thank you,
-Tim

**Comment by sheerun** [comment]
I've unregistered these packages but I'm unable to re-register because `git clone` with urls you provided don't work (are they public repositories? bower registry is for public projects).

You need to re-register these packages by yourself.
