### ISSUE TITLE
Please unregister kaazing-enterprise-javascript-client

### ISSUE THREAD

**Issue by ahousing** [bower/registry#196]
It appears that you can register a component anonymously, but not unregister.  We accidentally registered kaazing-enterprise-javascript-client.  (We have since correctly registered without the "javascript" in the name.)  Please either instruct how we can unregister kaazing-enterprise-javascript-client, or accomplish the same for us.  Thank you.

**Comment by sheerun** [comment]
I've unregistered package for you. There's `bower unregister` command for collaborators.

**Comment by ahousing** [comment]
I had found `bower unregister`, but as I understand it, you cannot unregister anonymously.  I didn't know how to deal with this problem, other than through this ticket.  Just FYI.
