### ISSUE TITLE
Move or remove dna-components

### ISSUE THREAD

**Issue by edoardocavazza** [bower/registry#197]
Could you please move `dna-components` package from:
https://gitlab.com/dna-components/dna-library
to:
https://github.com/Chialab/dna
or simply unregister it?

Thanks!

**Comment by sheerun** [comment]
You can unregister and register it again

**Comment by edoardocavazza** [comment]
I can't because it's a gitLAB repository :(

**Comment by sheerun** [comment]
I did it for you, sorry for delay

**Comment by edoardocavazza** [comment]
Thank you!
