### ISSUE TITLE
Unregister inexistant Bower Package

### ISSUE THREAD

**Issue by LeonardoGentile** [bower/registry#198]
Hello, I'm trying to register a package but it seems that my chosen name is taken. 
Although the github repo for the original package does not exist anymore. I've tried to contact the owner @benoror,  he tried to unregister it without success. Could you please unregister "angular-schema-form-datetimepicker" resolved to the inexistant repo "https://github.com/networknt/schema-form-datetimepicker.git" please?

**Comment by BenMann** [comment]
cc @desandro: 
Btw. many thanks for still handling the reregistering/unregistering stuff after such a long time! ❤️ 
Totally under-appreciated ;)

**Comment by sheerun** [comment]
Actually @desandro won't be able to help with unregistering anymore.

@LeonardoGentile I've unregistered package, you can register it again

@BenMann I made you registry editor, you can not unregister any package

**Comment by LeonardoGentile** [comment]
👍
