### ISSUE TITLE
How do change my registered package's git url?

### ISSUE THREAD

**Issue by mrak** [bower/registry#202]
Once upon a time I registered package `example`:

```
$ bower register example git://github.com/user/example.git
```

I have since changed my distribution strategy for this package, and have my built files for bower consumption now at `git://github.com/user/example-bower.git`.

There does not seem to be a way to seamlessly move the package's git url to the new location. It appears that the only way to do this is to submit an unregister request for the `example` package and then immediately re-register it at the new git url.

Are we missing something? Is there any equivalent to something like the following?

```
$ bower set-url example git://github.com/user/example-bower.git
```

**Comment by sheerun** [comment]
Yes, unfortunately that's true :( You need to unregister and then register again
