### ISSUE TITLE
wrong URL when package is searched on bower.io

### ISSUE THREAD

**Issue by jahtalab** [bower/registry#203]
opbeat-js should point to git://github.com/opbeat/opbeat-js-release
opbeat-angular should point to git://github.com/opbeat/opbeat-angular-release

they're registered correctly and can be installed from the correct endpoint but on bower.io website they point to an old repository

**Comment by jahtalab** [comment]
Is there any updates on this?

**Comment by sheerun** [comment]
@andrew Do libraries.io handle changes in bower registry?

**Comment by andrew** [comment]
@sheerun has @jahtalab changed the github repo for those packages? I didn't think you could change the mapping of name to repo?

**Comment by andrew** [comment]
I've updated those manually for you, about to go on holiday for a week so any others that have or will be changed will be resynced when I get back on Saturday.

**Comment by jahtalab** [comment]
thanks @andrew and @sheerun

**Comment by sheerun** [comment]
@andrew It's possible, one can unregister package and then re-register it under the same name..
