### ISSUE TITLE
Request: migrate package url

### ISSUE THREAD

**Issue by mrak** [bower/registry#204]
We'd like to update the repository url for the `braintree-web` package. Is it possible to do this from your end without any package downtime? i.e. without unregistering and having us manually re-register.

__OLD__ https://github.com/braintree/braintree-web.git
__NEW__ https://github.com/braintree/braintree-web-bower.git

Thanks in advance!

**Comment by sheerun** [comment]
Unfortunatly you need to unregister it and re-register again with downtime, there's no "rename"
