### ISSUE TITLE
Package alias

### ISSUE THREAD

**Issue by julmot** [bower/registry#205]
Assuming the following scenario:
- I would like to publish AngularJS to Bower
- There are several spellings – AngularJS, Angular.JS, Angular-JS, angularjs, angular.js, angular-js, angular, Angular
- I'd like to make the package available for all these spellings to avoid confused users when they get a different package as expected
- So I'm going to register the same repository for multiple names

This is already common. Then the following issues exist:
- Bower search differs between all these package names and sees them as autonomous and independent. This causes redundant results
- Users may installing a shorthand name because this is what they've found in the search

My solution proposal:
- Allow only one primary package name to be registered for one Git repository
- Allow up to 10 alias package names to be registered for one primary package name

Definition alias package:
- A package that is just a shorthand to the actual package name
- Will not appear in search results
- Exists to avoid confusion when users try to install "angular" but the actual package is named "angular.js" or "angularjs"
- Prevents a user from searching the correct spelling of a package name
- When installing a package using an alias the primary package name will be determined and saved in bower.json

Related to this issue:
- https://github.com/bower/bower/issues/2309#issuecomment-227402838

**Comment by sheerun** [comment]
I'd vote for normalizing to names of most popular npm packages with given repository url in package.json

**Comment by julmot** [comment]
> I'd vote for normalizing to names of most popular npm packages with given repository url in package.json

I'd vote against this, because:
- This would destroy the independence of Bower
- This is against a common workflow: Use Bower for web dependencies and npm for build and Node.JS. Many web applications aren't published to npm, so this would only work for packages that are also published on npm.
- This does not solve the alias issue. Popular packages may be listed in search results but aren't what a user expects.

**Comment by julmot** [comment]
Ping @bower/registry-editors

**Comment by sheerun** [comment]
Bower is deprecated in favor of npm packages namespace so it's not relevant anymore.. sorry
