### ISSUE TITLE
Package registered twice, once with incorrect capitalisation in package name.

### ISSUE THREAD

**Issue by jesseyuen** [bower/registry#206]
I've registered https://github.com/humaan/Modaal/ on Bower today, once accidentally with the name _Modaal_ (capital M), and then again with the correct spelling _modaal_. 

I've been unsuccessful in deleting the first instance with the capital letter using:

`bower unregister <package>`

Is it best practice to have the capital _M_ version removed or to leave both registered? Sorry to bother!

**Comment by sheerun** [comment]
done

**Comment by jesseyuen** [comment]
Hi @sheerun  - so sorry to bother you again. I notice that in a package search on bower.io, Modaal is still indexed with a capital _M_ only, and no results are available if searching for _modaal_ in lowercase. Is there anything I need to do to enable only _modaal_ in lowercase to return or is it a matter of time to re-index? Thanks again.

**Comment by sheerun** [comment]
Actually bower cli search works just fine, the web version is hosted by libraries.io, and it doesn't support case insensitive search and removing / changing registty entries. I think @andrew will work on it next week

**Comment by jesseyuen** [comment]
Brilliant - thanks again.
