### ISSUE TITLE
Update bower registry after git repo rename

### ISSUE THREAD

**Issue by soumak77** [bower/registry#209]
I recently registered the `angular-base-apps` package on bower.  The package was registered against git://github.com/base-apps/angular-base.git, but I renamed it to git://github.com/base-apps/angular-base-apps.git.  How can I fix this?

**Comment by BenMann** [comment]
@soumak77 I could unregister the package, so you can register it again with correct data. Lemme know if I should!

**Comment by soumak77** [comment]
Since github setup a redirect from `git://github.com/base-apps/angular-base.git` to `git://github.com/base-apps/angular-base-apps.git` I think this can be closed.  Would there be any other reason to re-register?

**Comment by BenMann** [comment]
Not that I can think of 😉 
Closing 💃
