### ISSUE TITLE
Bower should ask for login before registering

### ISSUE THREAD

**Issue by WoLpH** [bower/registry#211]
It seems that bower only asks for a login when unregistering and not when registering. The result is that I've registered the RaphBoard package today which I can't modify or change anymore.

Can anyone change the url to https://github.com/WoLpH/RaphBoard instead?

**Comment by BenMann** [comment]
@WoLpH Since the package (`RaphBoard`) wasn't available for install anymore anyway, I just unregistered the package. All yours to register again if you wish. 🍰

**Comment by WoLpH** [comment]
Thanks @BenMann :)
