### ISSUE TITLE
Wrong url, could you please correct or unregister seven-segment-element ?

### ISSUE THREAD

**Issue by potens1** [bower/registry#212]
Hi, I've done a mistake when registering my package, could you please unregister the seven-segment-element or change the repository url from https://gitlab.com/potens1/seven-segment-element/
 to https://gitlab.com/potens1/seven-segment-element.git ?

Thank you.

**Comment by potens1** [comment]
Hi,
Please, can someone have a look to this ?

Thank you

**Comment by sheerun** [comment]
done

**Comment by sheerun** [comment]
and sorry for huge delay...
