### ISSUE TITLE
Question: How to retain past versions and switch homepage of a package

### ISSUE THREAD

**Issue by CITguy** [bower/registry#217]
I've inherited a project where it was set up to push assets to a separate repo for bower distribution. However, I would like to modify the registration to use the source repo instead.
Is it possible to do this without losing references to older versions of my package?

Scenario:
- I have a github project whose source is located at the `foo/bar` github repo.
- The registration uses the `foo/bar-bower` github repo for purposes of bower distribution.

Is it possible to retain past releases and modify registration to distribute from `foo/bar` instead?

**Comment by sheerun** [comment]
It's not possible with bare bower. Maybe there are some re-writing plugins like bower-installer
