### ISSUE TITLE
Unregisterpackage hosted by BitBucket

### ISSUE THREAD

**Issue by SadPandaBear** [bower/registry#218]
I've registered a wrong repository of mine.

Would you please take care of that?

url: https://bitbucket.org/SadPandaBear/hub-of-legends

**Comment by BenMann** [comment]
@SadPandaBear there is no package with the name `hub-of-legends` registered ..your `bower.json` states the package name is `my-app` which also doesn't exist as a package.. What did you register it as?

**Comment by SadPandaBear** [comment]
@BenMann Sorry, It's listed as "dragontail-portable"

**Comment by BenMann** [comment]
@SadPandaBear Alright, unregistered and all yours ;-)
