### ISSUE TITLE
chart.js package transfer

### ISSUE THREAD

**Issue by simonbrunel** [bower/registry#219]
Hi guys,

Chart.js is currently working on [re-adding native support of Bower](/chartjs/Chart.js/pull/3223). Could you please transfer *chart.js* alias to that repository: https://github.com/chartjs/Chart.js.git. It currently points on a **dead** repository, we contacted the owner but no reply received (yet). Some of our users are confused when trying to install chart.js via bower, thinking it's our package:

    Repository not found. fatal: repository 'https://github.com/centralway/chart.js.git/' not found

https://github.com/chartjs/Chart.js/issues/3081#issuecomment-239604775
https://github.com/chartjs/Chart.js/issues/1949

**Comment by BenMann** [comment]
@simonbrunel there is a package called `chartjs` which seems to work correctly. I understand having a package named `chart.js` which points to a dead end is rather confusing. I think we could unregister the dead package, so you're able to register it with the "right" repo. Would that be okay?

Have you heard back from the original owner? I think we should give it a week at least for someone to reply 😉

**Comment by simonbrunel** [comment]
@BenMann, this solution works for me. I received news from the original contributors ([listed on this page](https://libraries.io/github/centralway/chart.js)), but they are not anymore with Centralway so can't take any decision about that package. They redirected me to someone in this company, so hopefully I should have a reply soon.

Just curious, what is your policy about *dead* packages?

**Comment by BenMann** [comment]
@simonbrunel Not sure there is a policy, which is why I'm rather carefully waiting at the moment. It's always been a "register it first and it's yours" approach and unregistering is 99% of the time because someone want's to move/rename the package or some kind of error on the owner's side. 

However Contacting the current owner seems like a reasonable thing to do 👍.
I don't expect them to insist on the package-nam, as it's a seemingly dead project...

**Comment by BenMann** [comment]
Any updates?

**Comment by simonbrunel** [comment]
Last e-mail sent on September 2 but unfortunately no news since.

**Comment by BenMann** [comment]
Okay, I'd say let's wait until the end of this week. If nobody who is still affiliated with that package surfaces until then, I'd just unregister it, so you can claim it.

**Comment by simonbrunel** [comment]
@BenMann, nothing moved on our side, do you think we should wait more?

**Comment by BenMann** [comment]
@simonbrunel I just unregistered the package. All yours! 📦 
In case one of the original owners replies at some point, let me know.

**Comment by simonbrunel** [comment]
Thanks a lot @BenMann :)
