### ISSUE TITLE
Unregister gitlab project

### ISSUE THREAD

**Issue by ganlanyuan** [bower/registry#220]
Hey, does bower support gitlab?
I have a project registered as `selectivizr-update` and `selectivizr-will`, but I couldn't `bower install` them correctly. I always get the result:

```
bower cached        https://gitlab.com/will1028/selectivizr#e-tag:W/"cc36f06
bower validate      e-tag:W/"cc36f06 against https://gitlab.com/will1028/selectivizr#*
bower new           version for https://gitlab.com/will1028/selectivizr#*
bower resolve       https://gitlab.com/will1028/selectivizr#*
bower download      https://gitlab.com/will1028/selectivizr
bower resolved      https://gitlab.com/will1028/selectivizr#e-tag:W/"20f0381

Unable to find a suitable version for selectivizr-update.
```

What is right way to register if the project is on gitlab?
If gitlab is not supported, please could you remove them? I will move it to github.

Much thanks

**Comment by iamso** [comment]
I am also interested in this. Why does unregistering a package, that is not on github, not work?

**Comment by sheerun** [comment]
@iamso Because it's not implemented in registry
@ganlanyuan I've unregistered these packages. Please try to register something like `https://gitlab.com/will1028/selectivizr` returns 404. Also, please register with .git extension

**Comment by ganlanyuan** [comment]
thanks
