### ISSUE TITLE
Wrong username in repo URL

### ISSUE THREAD

**Issue by faribauc** [bower/registry#222]
Hi,

Please change the repo URL on package "featuretoggle-lib-js" from

https://christophefaribault@bitbucket.org/featuretoggle/lib-js.git

to

https://featuretoggle@bitbucket.org/featuretoggle/lib-js.git

Also, please remove the "featuretoggle-lib-js-2" package, which is a duplicate I registered too make sure the second URL was valid.

Thanks

**Comment by sheerun** [comment]
done
