### ISSUE TITLE
package js-rich-marker is registered to the wrong GitHub Repo

### ISSUE THREAD

**Issue by seafoodbuffet** [bower/registry#223]
the js-rich-marker package in Bower is currently registered against this repo:
https://github.com/ashsidhu/js-rich-marker
This repo is inactive and the default branch of this repo lacks a valid bower.json

instead, it should be registered to this repo:
https://github.com/googlemaps/js-rich-marker which is both active and correct

**Comment by sheerun** [comment]
Please ask @ashsidhu to unregister this component and re-register it under now repo. We can't force it.
