### ISSUE TITLE
Request to unregister packages or have repo locations updated

### ISSUE THREAD

**Issue by koreyconway** [bower/registry#228]
Package: 2klic-sdk
Current: https://bitbucket.org:2klicdev/2klic-sdk
Repo: git@bitbucket.org:2klicdev/2klic-sdk.git

Package: 2klic_io-sdk
Current: https://jolava@bitbucket.org/2klicdev/2klic_io-sdk.git
Repo: git@bitbucket.org:2klicdev/2klic-sdk.git

**Comment by koreyconway** [comment]
The wait time is getting ridiculous. Can someone clean this out already? I need to use the namespace. And please help everyone else who is waiting indefinitely for a similar problem.

**Comment by sheerun** [comment]
done
