### ISSUE TITLE
How to push my bitbucket repository to bower private registry?

### ISSUE THREAD

**Issue by tarun29061990** [bower/registry#229]
curl http://bower.herokuapp.com/packages -v -F 'name=builder' -F 'url=https://tarun29061990@bitbucket.org/livspaceeng/builder.git'

Its failing giving invalid URL error

**Comment by tarun29061990** [comment]
Tried with this curl http://bower.herokuapp.com/packages -v -F 'name=builder' -F 'url=git://bitbucket.org/livspaceeng/builder.git'

Getting this log:-
 Connected to bower.herokuapp.com (23.23.167.77) port 80 (#0)
> POST /packages HTTP/1.1
> Host: bower.herokuapp.com
> User-Agent: curl/7.49.1
> Accept: */*
> Content-Length: 281
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------37adeb2f2d171c9c
>
< HTTP/1.1 100 Continue
< HTTP/1.1 503 Service Unavailable
< Connection: keep-alive
< Server: Cowboy
< Date: Tue, 25 Oct 2016 14:30:10 GMT
< Content-Length: 484
< Content-Type: text/html; charset=utf-8
< Cache-Control: no-cache, no-store
* HTTP error before end of send, stop sending
<
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
* Closing connection 0

**Comment by sheerun** [comment]
You cannot. Bower registry hosts public repositories
