### ISSUE TITLE
Allow endpoints other than git endpoints?

### ISSUE THREAD

**Issue by satazor** [bower/registry#23]
Follow up of: https://github.com/bower/bower/issues/22

**Comment by noahmonster** [comment]
I'd like to shed some light on what the current behavior is.  I'm trying to provide an internal company project via our own private registry.  All of our code is in SVN repositories.  When I tried to register my project, I got an Invalid URL format error:

```
> bower register common-ui svn+https://my-company-project
...
? Registering a package will make it installable via the registry (http://localhost:3000), continue?: Yes
...
bower                       EINVFORMAT Invalid URL format
```

I ended up setting `skipValidation: true` in my config, which allowed me to register the above URL successfully.  The URL also worked when I used bower to install my project from this private registry.  The point being that this is not an invalid URL.

It seems to me that this project is specifically designed to allow private registries to provide whatever they want from any source (especially SVN).  So, if not explicitly allowing SVN URLs, there should at least be a good error message, as @rafayepes stated.

**Comment by patrickkettner** [comment]
what version of the registry are you using

**Comment by noahmonster** [comment]
Master, pulled today.

**Comment by patrickkettner** [comment]
@noahmonster, apologies - I hadn't looked in this in a while I remembered incorrectly.

As of now, the registry is only validates git urls. see [validUrl](https://github.com/bower/registry/blob/c47b753c22522ba72ed15f8f36d966400a3fd3d4/lib/validURL.js)

It would be trivial to add `svn ln` to that, but heroku (where we run the registry) does not have svn built in, nor am I sure of how you would go about getting it since it does not have sudo.

**Comment by noahmonster** [comment]
Would it be possible to tie the validation of URLs to some configuration values.  More than just the `skipValidation` flag.  Would it be possible to have an `allowSVN` configuration value?  This would solve my issue without having to turn off validation completely.  It would also allow a git only configuration as is being used currently.

**Comment by patrickkettner** [comment]
PRs welcome!
