### ISSUE TITLE
moving Mocha's url

### ISSUE THREAD

**Issue by boneskull** [bower/registry#235]
Per mochajs/mocha#2615, we want to change Mocha's repo URL at some point.

I understand I'll need to file an issue here *when the time comes*.  Also, I'll need write permission to the registered package, whatever that entails--I was not involved w/ Mocha when it was registered with Bower.  

Are these permissions based on GitHub?  There's no way for me to test it (to my knowledge) other than to use `unregister`.

**Comment by sheerun** [comment]
@boneskull Contributors of project are able unregister these projects from bower and re-register them again. If you need my assistance when the time comes, please write to me directly at: sheerun@sher.pl
