### ISSUE TITLE
Fetch latest package version

### ISSUE THREAD

**Issue by segrey** [bower/registry#239]
Is there a way to fetch latest version for a package?
Tried https://bower.herokuapp.com/packages/jquery, but it doesn't contain version:
```
{"name":"jquery","url":"https://github.com/jquery/jquery-dist.git"}
```

**Comment by sheerun** [comment]
you can use `bower info jquery` or use `git ls-remote` to list tags of remote repository. bower uses tags that look like semver for versions (with and without `v` prefix)

**Comment by segrey** [comment]
Thanks a lot!
