### ISSUE TITLE
Unregistered repo can't be registered with same URL

### ISSUE THREAD

**Issue by kirill-konshin** [bower/registry#241]
Steps:

1. Register a repo with GitHub URL and make typo in repo name
2. Unregister immediately
3. Try to register with proper name
4. Get an error EDUPLICATE Duplicate package
5. Do `bower info %pkgname%` and get `ENOTFOUND Package %pkgname% not found`

I suppose that since package has been unregistered, it should be possible to register it again under different or even under the same name.

**Comment by sheerun** [comment]
it should be the case actually, I never had any issues with it
