### ISSUE TITLE
Re-register SVG.js

### ISSUE THREAD

**Issue by dotnetCarpenter** [bower/registry#248]
We have change the home of [SVG.js](https://svgdotjs.github.io/) from wout to svgdotjs.

Our new URL: `git@github.com:svgdotjs/svg.js.git`

I've tried to change the URL my self by [unregister/register but I don't have access to unregister SVG.js](https://github.com/bower/registry/issues/157#issuecomment-279083433)

Ref: https://github.com/svgdotjs/svg.js/issues/586

**Comment by dotnetCarpenter** [comment]
We're beginning to get [more complaints](https://github.com/svgdotjs/svg.js/issues/586#issuecomment-279737205) about bower pointing to the wrong svg.js repo.
Does anyone have information about how I can do the change via a PR or other means?

**Comment by nopantsmonkey** [comment]
until unresolved please restore the svg.js repo

**Comment by sheerun** [comment]
Hey,

Sorry for the delay. I've moved the repo to svgdotjs. Please notice `bower cache clean` might be needed on clients for bower to recognize new repository.
