### ISSUE TITLE
Change jquery-form repo URL

### ISSUE THREAD

**Issue by kevindb** [bower/registry#249]
The [jquery-form](https://github.com/jquery-form/form) project has changed ownership and the repo URL has changed. Would you please update the URL?

OLD:  
`https://github.com/malsup/form.git`  

NEW:
`https://github.com/jquery-form/form.git`

**Comment by kevindb** [comment]
I'm just checking to see if there's anything I can do on my end to be more helpful in resolving this issue. I'm happy to submit a pull request, but I'm not sure where the registry data is stored (or even if it's open sourced).

**Comment by sheerun** [comment]
done it, sorry for the delay

**Comment by kevindb** [comment]
Thank you!
