### ISSUE TITLE
unregister package with incorrect gitlab url

### ISSUE THREAD

**Issue by wookoouk** [bower/registry#255]
As with https://github.com/bower/registry/issues/220 a user (Phil) has registered a package and missed the .git, he was then unable to authenticate to remove the package because he authenticates with github, the transcript can be found in the #support chat in discord.

```
Hi
quick question
I registered a packagename with a gitlab.com endpoint that is missing the .git in the end...
Now versions don't get picked up.
Anyone here, who can fix this? If there is a donate coffee button somewhere, I'm happy to supply coffee for the task :smiley:
the package in question is dees-header -> change required: add .git to the endpoint
since I cannot login with gitlab I can't do so it myself...
sorry for the trouble
```

**Comment by wookoouk** [comment]
the package name on bower is dees-header

**Comment by philkunz** [comment]
hi, Phil here. :) Would be awesome if we could correct this mistake of mine :) Also looking into submitting a PR with regex validation that prevents submitting gitlab URLS without .git at the end.

**Comment by philkunz** [comment]
@sheerun ... any opinion here? :)

**Comment by sheerun** [comment]
@philkunz I've unregistered it. Hope it helps :)
