### ISSUE TITLE
bower EUNKNOWN Can only unregister packages hosted on GitHub.com

### ISSUE THREAD

**Issue by SpEcHiDe** [bower/registry#256]
I want to transfer the package `smc-fonts` from https://gitlab.com/calicut-us/smc-fonts-bower to https://gitlab.com/smc/smc-fonts-bower

**Comment by SpEcHiDe** [comment]
On further thought, it is better to unregister the `smc-fonts` name! I registered the name `fonts-smc`!

**Comment by sheerun** [comment]
it's probably not needed anymore, but I've done it, sorry for the delay
