### ISSUE TITLE
Unregister package which is pointed to Bitbucket repo without version tag

### ISSUE THREAD

**Issue by crreddys** [bower/registry#258]
I created a package pointing to bitbucket repo which doesnt have version tags. Trying to unregister it and its not allowing me to do since its bitbucket repo. I added version tags to repo after registering and the package is not getting updated. 

Can any of you please unregister my package "cf-ui-polymer".

**Comment by crreddys** [comment]
Also please unregister my test package as well "cf-ui-polymer-test"

**Comment by sheerun** [comment]
it's probably outdated and not needed anymore, but I've done it anyway, sorry for the delay
