### ISSUE TITLE
Change Git endpoint for nevis package

### ISSUE THREAD

**Issue by neocotic** [bower/registry#261]
The `nevis` package has recently been transferred to another GitHub organisation. While I have updated this in `bower.json`, I see no way of making the change to the Git endpoint on the registry.

Can someone please change the Git endpoint for me?

Old | New
--- | ---
https://github.com/Skelp/nevis.git | https://github.com/NotNinja/nevis.git

**Comment by sheerun** [comment]
done, sorry for huge delay..

**Comment by neocotic** [comment]
Thank you
