### ISSUE TITLE
unregister plottable

### ISSUE THREAD

**Issue by hellochar** [bower/registry#268]
Hey bower,

I'm the new maintainer of the Plottable open source project (https://github.com/palantir/plottable) and we're moving away from bower - I tried to follow the unregister steps at https://bower.io/docs/creating-packages/#unregister but I don't know the credentials for the Plottable bower account. Could we get the package removed?

Thanks,
Xiaohan

**Comment by AkcentChester** [comment]
Hey bower,

I'm the new maintainer of the Plottable open source project (https://github.com/AkcentChester/html-pack) and we're moving away from bower - I tried to follow the unregister steps at https://bower.io/docs/creating-packages/#unregister but I don't know the credentials for the Plottable bower account. Could we get the package removed?

Thanks,
Chester

**Comment by sheerun** [comment]
If you still want to unregister / modify this package (these packages) you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package (these packages). Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
