### ISSUE TITLE
Way to make local replica of bower registry

### ISSUE THREAD

**Issue by eugeneware** [bower/registry#27]
Is there a way to make a local bower.io registry clone?

With the npm registry you can use couchdb and make your own repo, which is useful for getting access to components when there is limited connectivity.

We recently had a [camp](http://campjs.com) where we had limited connectivity, and a local npm registry was awesome. Next year we'd like to do that with bower too.

I know I can get access via:

https://bower-component-list.herokuapp.com
https://bower.herokuapp.com/packages

But is there a better way to take a local copy of the repo and host a local server?

**Comment by sheerun** [comment]
https://bower.herokuapp.com/packages lists all available data
