### ISSUE TITLE
Unregister  'angular-signalr-core-hubs'

### ISSUE THREAD

**Issue by fabiogusmao** [bower/registry#271]
I am moving source code to GitHub so please unregister the old one. No one depends on it yet because I just created it today. 

I'll even change the name to `angular-signalr-core-hub` because it sounds better :)

**Comment by sheerun** [comment]
If you still want to unregister / modify this package (these packages) you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package (these packages). Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
