### ISSUE TITLE
Move registry-image-widgets location

### ISSUE THREAD

**Issue by petervo** [bower/registry#272]
Are you able to move registry-image-widgets from

https://github.com/openshift/registry-image-widgets

to
 
https://github.com/cockpit-project/registry-image-widgets.git

Or is there a different way to go about getting that changed?

**Comment by sheerun** [comment]
If you still want to unregister / modify this package (these packages) you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package (these packages). Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
