### ISSUE TITLE
Unregister 'pixel-code-grid' package

### ISSUE THREAD

**Issue by thijskaspers** [bower/registry#273]
I'm moving the package 'pixel-code-grid' from Bitbucket to Github, so I'd like to unregister it. Nobody is depending on the package yet, as we've just created it.

Thanks in advance!

**Comment by sheerun** [comment]
If you still want to unregister / modify this package (these packages) you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package (these packages). Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
