### ISSUE TITLE
Unregister chops-ui package

### ISSUE THREAD

**Issue by jojwang** [bower/registry#274]
It was created a day ago. No one is using about it or even knows about it.

**Comment by sheerun** [comment]
done

**Comment by annajowang** [comment]
The old chops-ui package still seems to exist.
I just tried:
bower register chops-ui <new git endpoint URL>

and when I run:
bower info chops-ui
I get
bower chops-ui              cached <old git endpoint URL>

**Comment by sheerun** [comment]
maybe try "bower cache clean"

bower info chops-ui                                                                                  ✘ 127
bower                        ENOTFOUND Package chops-ui not found

**Comment by annajowang** [comment]
Thanks!
