### ISSUE TITLE
Unregister packages itaca-ng-*

### ISSUE THREAD

**Issue by simonered** [bower/registry#276]
Could you please unregister the following packages (from bitbucket)?

- itaca-ng-utils
- itaca-ng-filters
- itaca-ng-services
- itaca-ng-directives
- itaca-ng-components

**Comment by simonered** [comment]
Please, I need to update the git repository with the new one @ github.
Could you please delete the old ones?
 It's quite urgent. 
Thank you.

**Comment by sheerun** [comment]
If you still want to unregister / modify this package you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package. Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
