### ISSUE TITLE
Unregister paperjs package

### ISSUE THREAD

**Issue by Jolg42** [bower/registry#278]
Hi!

Someone is trolling [the official Paper.js repository](https://github.com/paperjs/paper.js) with a package with the same name on Bower and it only contains an "epic sax guy" video.
Source code: https://github.com/kmakblob/paperjs/blob/master/paper.js

See issues https://github.com/kmakblob/paperjs/issues/1 and https://github.com/paperjs/paper.js/pull/1150 for reference.

Could you unregister it? We reported it to GitHub too with @lehni

Thanks!

**Comment by sheerun** [comment]
Sure, I've re-registered to https://github.com/paperjs/paper.js

`bower cache clean` might be necessary for refresh on clients

**Comment by Jolg42** [comment]
Thanks @sheerun!
Have a nice day 😉

**Comment by lehni** [comment]
@sheerun @Jolg42 thank you both for looking into this!
