### ISSUE TITLE
Unregister Purescript Electron

### ISSUE THREAD

**Issue by cjduncana** [bower/registry#279]
I’m taking over a [package](https://github.com/bamboo/purescript-electron) that the owner stopped developing on. I talked to the owner to have his package unregistered on bower to upload mine, and he did so. The problem that I have is that when I register my package, the registry still show information of the previous package. I am able to successfully register my package, yet when I want to download it using bower, the previous package is downloaded instead.

Can you unregister purescript-electron, so that I can upload my package?

**Comment by sheerun** [comment]
If you still want to unregister / modify this package you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package. Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
