### ISSUE TITLE
unregister gunui-slider

### ISSUE THREAD

**Issue by Stefdv** [bower/registry#280]
Please unregister it because bower can't find it...i want to register the new package

**Comment by sheerun** [comment]
If you still want to unregister / modify this package you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package. Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
