### ISSUE TITLE
unregister ungryfox/font-roboto, register PolymerElements/font-roboto

### ISSUE THREAD

**Issue by BlietZ** [bower/registry#281]
As stated in the title, please unregister the font-roboto from ungryfox : https://github.com/ungryfox/font-roboto
and register the font-roboto from PolymerElements: https://github.com/PolymerElements/font-roboto

There is an issue in the ungryfox  version with deprecated styling using Html Imports: https://bugs.chromium.org/p/chromium/issues/detail?id=523952

The PolymerElements/font-roboto is being updated.

**Comment by sheerun** [comment]
If you still want to unregister / modify this package you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package. Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with bower cache clean for each user. At this point it's better to leave registry entries unmodified, they won't hurt anyone.
