### ISSUE TITLE
Please unregister purescript-graphql

### ISSUE THREAD

**Issue by ethul** [bower/registry#284]
ethul/purescript-graphql#1

**Comment by sheerun** [comment]
You can do it by yourself, there's `bower unregister` command

**Comment by sheerun** [comment]
If it doesn't work you can try to update bower first

**Comment by ethul** [comment]
Thanks. I did try to unregister using bower 1.8.4, but no luck yet.

**Comment by sheerun** [comment]
OK, I unregistered it for you

**Comment by sheerun** [comment]
curl https://registry.bower.io/packages/purescript-graphql

**Comment by sheerun** [comment]
you also need to do bower cache clean to see changes locally as bower caches most of registry requests

**Comment by ethul** [comment]
Thank you very much for your help!
