### ISSUE TITLE
Change Git endpoint for pollock package

### ISSUE THREAD

**Issue by neocotic** [bower/registry#285]
The `pollock` package has recently been transferred from a GitHub organisation to my user. While I have updated this in `bower.json`, I see no way of making the change to the Git endpoint on the registry.

Can someone please change the Git endpoint for me?

Old | New
--- | ---
https://github.com/NotNinja/pollock.git | https://github.com/neocotic/pollock.git

**Comment by sheerun** [comment]
If you still want to unregister / modify this package you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package. Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with `bower cache clean` for each user.
