### ISSUE TITLE
Changed github endpoint for the svg.js package

### ISSUE THREAD

**Issue by Fuzzyma** [bower/registry#287]
We moved our bower-ready files to [svg.js-bower](https://github.com/svgdotjs/svg.js-bower.git) and will start taging them there from 3.0 upwards.

Can you change the registry in a way, that users of old versions still get the right tag? And users requesting svg.js v3 and above will use the new repo?

|Old|New|
|----|-----|
|https://github.com/svgdotjs/svg.js.git|https://github.com/svgdotjs/svg.js-bower.git|

**Comment by sheerun** [comment]
It's not possible, you can only point to one repository

**Comment by Fuzzyma** [comment]
well in that case, let the endpoint as it is for now. I might just register a new package for version 3 and above

**Comment by sheerun** [comment]
Major bump in semver should be enough

**Comment by Fuzzyma** [comment]
@sheerun but when the github endpoint changes, every version below 3.0 is not accessible via bower anymore. Or are these versions cached in your servers?

**Comment by sheerun** [comment]
If you still want to unregister / modify this package you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package. Please also mind that even if we remove/modify entry in bower registry, bower clients can have cache saved which needs to be cleaned with `bower cache clean` for each user.
