### ISSUE TITLE
Unregister package sid-instant-eft-popup

### ISSUE THREAD

**Issue by Sid-InstantEFT** [bower/registry#288]
We initially registered the package 'sid-instant-eft-popup' using a BitBucket git repository (https://brandonpearman@bitbucket.org/sidinstanteft/sid-instant-eft-popup/src/master/)

We now want to move this to GitHub as we are leaving BitBucket, but unfortunately I am unable to unregister a package that is not hosted on GitHub.com

Can the current package please be removed?

**Comment by sheerun** [comment]
If you still want to unregister / modify this package you can send PR against this repository that modifies db/packages.json file. Please include proof that you are owner of this package.
