### ISSUE TITLE
Bower install | CERT_HAS_EXPIRED |  bower certificate issue since 24 April

### ISSUE THREAD

**Issue by azajkhan** [bower/registry#305]
When executing bower install.
its giving error 
bower textAngular#1.4.6 CERT_HAS_EXPIRED Request to https://registry.bower.io/packages/textAngular failed: certificate has expired

bower angular-route#1.3.x CERT_HAS_EXPIRED Request to https://registry.bower.io/packages/angular-route failed: certificate has expired
What i tried:
1. bower cache clean ( didn't worked)
2. added  "strict-ssl": false in .bowerrc file and it worked for now.

We need this  CERT_HAS_EXPIRED issue to be fixed asap.

**Comment by galregev** [comment]
Same issue on my CircleCI & Jenkins jobs.

**Comment by sheerun** [comment]
Merging with #304

**Comment by azajkhan** [comment]
**Still facing issues 
14:14:32  bower oauth-js#0.4.8           
 CERT_HAS_EXPIRED Request to https://registry.bower.io/packages/oauth-js failed: certificate has expired**

**Comment by azajkhan** [comment]
faced another issue 
**14:22:14  bower angular-recaptcha#4.2.0   CERT_HAS_EXPIRED Request to https://registry.bower.io/packages/angular-recaptcha failed: certificate has expired**
