### ISSUE TITLE
Cache GitHub data

### ISSUE THREAD

**Issue by sindresorhus** [bower/registry#34]
We should cache GitHub data like stars/etc with packages in the registry so it can be presented in package requests, cli/web search, etc. Could be refreshed once a week.

**Comment by sheerun** [comment]
This were moved to search server..

**Comment by sindresorhus** [comment]
Nope, this should eventually be a part of the real registry. The search server is just a temporary hack begging to be put down.

**Comment by sheerun** [comment]
Official registry won't support star counts, the load is already too high for any extra functionality.

One can always create 3rd party app to fetch github data, like we do with bower.io/search
