### ISSUE TITLE
Download stats

### ISSUE THREAD

**Issue by aexmachina** [bower/registry#39]
It would be useful for the community to be able to see the number of downloads for each module in the same way as you can on https://npmjs.org/. This is a simple metric that helps people to see how widely-used a module is, and helps people to choose which modules to try if there's a number of options.

**Comment by bpulito** [comment]
+1

**Comment by sheerun** [comment]
Unfortunately the only reliable way to count downloads is to ask github for it.

Registry results are cached locally so any counters we had would not be reliable (we don't have any)
