### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by sindresorhus** [bower/registry#42]
When the rewrite is done it would be nice to have a Docker image so it's super easy to get set up. A lot of people use Bower inside their companies.

Relevant: https://github.com/terinjokes/docker-npmjs

**Comment by sheerun** [comment]
Registry setup is now easier. Only PostgreSQL installed is necessary: https://github.com/bower/registry/commit/66e074a506c18be83ae3533c9a59dd11b54ba5e4

This means Dockerfile is no longer needed :) Closing.
