### ISSUE TITLE
Github login

### ISSUE THREAD

**Issue by wibblymat** [bower/registry#49]
As mentioned at a meeting recently, it would be good to delegate user management to someone else. Github is a logical choice for us.

The API uses OAuth2, and offers a method for checking that a [user is a collaborator](http://developer.github.com/v3/repos/collaborators/#get) on a repo - handy for letting people take ownership of current packages when we add auth.

There is a snag though. There are two ways that a user could log in from the command line. The first is that they can give the bower client their github username and password directly. The second involves redirecting the user to the github webpage to finishing authorisation. Neither feels great. Do we have any alternatives, or preferences for which of these we use?

@satazor @benschwarz @svnlto @paulirish @sindresorhus @necolas

**Comment by desandro** [comment]
Closing now that Bower v1.4.0 has shipped with `bower login`
