### ISSUE TITLE
Contributions?

### ISSUE THREAD

**Issue by cgross** [bower/registry#52]
Hi - I have some time over the next 2 or 3 weeks.  I was wondering if the team is looking for contributions to the registry work.  If so, and if there was something that could be sliced off, I'd be happy to devote some time.

**Comment by sheerun** [comment]
Nowadays it's clear that bower won't create another registry with ability to upload binaries.

Npm's registry already provides great way to upload binaries and common name space. The only way we could improve the situation is to make easier to download package from npm registry with bower.

That's for another issue though
