### ISSUE TITLE
Query by tag

### ISSUE THREAD

**Issue by jugglinmike** [bower/registry#63]
I'd like to be able to query the registry according to package tags.

I'm maintaining a JavaScript framework for authoring visualizations. If I could query the registry by tag, I could extend my website with a dynamic listing of all modules that utilize my framework. This would help users discover and re-use code authored by others.

This functionality would go a long way towards #14. Even if bower continues to omit dependency information from search results, I could author a backend process to scrape this information from the packages' git repositories directly. At the moment, though, the simple string search exposed by the registry is too imprecise to depend on for my use case.

**Comment by sheerun** [comment]
Unfortunately to support querying by tags we'd need to scrape them from repositories on github. This would make registry much more complex and we want to make it as simple as possible.

It could be possible for 3rd party to create search engine for bower packages though.
