### ISSUE TITLE
Squatter on dt-node

### ISSUE THREAD

**Issue by jedmao** [bower/registry#98]
It would seem that there's a squatter on [dt-node](https://github.com/dt-bower/dt-node). I've had a pull request up there for 4 months w/o any response whatsoever.

I registered [dt-node-jedmao](https://github.com/jedmao/dt-node) in the interim, but it's unfortunate I had to do this.

Anything that can be done?

**Comment by sheerun** [comment]
You can fill request in bower/bower#120
