### ISSUE TITLE
[Validation] Disallow multiple package names from pointing to the same endpoint

### ISSUE THREAD

**Issue by benschwarz** [bower/registry#99]
It is currently possible to register: 

`angular_JS` :arrow_right:  `angularjs/bower-angular`
`angulerjs` :arrow_right:  `angularjs/bower-angular`
and

`angularjs` :arrow_right: `angularjs/bower-angular`

Instead, we should validate that only a single registration can be made per endpoint.

**Comment by sheerun** [comment]
Why aliases are bad? Maybe we just need to hide them from search.

**Comment by desandro** [comment]
Cons with aliases is that they are confusing. It's not clear if there's a different between one package name or another, even if they are pointing to the same repo. They might all dilute our stats.

I don't think we need to eliminate them, but having `anguler` pop up in results seems like a bad experience.

**Comment by sheerun** [comment]
Aliases are OK. We can't remove them because of backward compatibility :(

It's quite possible some packages already use misspelled names. The best we can do is:

- Remove misspelled aliases from search
- Display notifications during installation that package name is misspelled

**Comment by davidjbradshaw** [comment]
The web search dedupes the results, whilst still allowing for any alias to be looked up.

https://github.com/bower/search/pull/47

I could patch the cmd search to do the same thing if that is helpful.

**Comment by sheerun** [comment]
I thnk it's already done.
